import type { Name } from "@/lib/names/types";

export const middleEastNames: Name[] = [

// BAHRAIN

{ name: "Fatima", gender: "girl", urduMeaning: "پاکیزہ، نبی ﷺ کی بیٹی کا نام", englishMeaning: "Pure, one who abstains", origin: "Arabic", religion: "Islamic", country: "Bahrain" },
{ name: "Maryam", gender: "girl", urduMeaning: "پاکیزہ، عبادت گزار", englishMeaning: "Pure, devoted", origin: "Arabic / Hebrew", religion: "Islamic", country: "Bahrain" },
{ name: "Noor", gender: "girl", urduMeaning: "روشنی", englishMeaning: "Light", origin: "Arabic", religion: "Islamic", country: "Bahrain" },
{ name: "Huda", gender: "girl", urduMeaning: "ہدایت", englishMeaning: "Guidance", origin: "Arabic", religion: "Islamic", country: "Bahrain" },
{ name: "Aisha", gender: "girl", urduMeaning: "زندہ، خوشحال", englishMeaning: "Alive, prosperous", origin: "Arabic", religion: "Islamic", country: "Bahrain" },
{ name: "Mariam", gender: "girl", urduMeaning: "پاکیزہ", englishMeaning: "Pure", origin: "Arabic", religion: "Islamic", country: "Bahrain" },
{ name: "Zainab", gender: "girl", urduMeaning: "خوشبودار پھول", englishMeaning: "Fragrant flower", origin: "Arabic", religion: "Islamic", country: "Bahrain" },
{ name: "Sara", gender: "girl", urduMeaning: "شہزادی، معزز خاتون", englishMeaning: "Princess, noblewoman", origin: "Arabic / Hebrew", country: "Bahrain" },
{ name: "Amal", gender: "girl", urduMeaning: "امید", englishMeaning: "Hope", origin: "Arabic", country: "Bahrain" },
{ name: "Reem", gender: "girl", urduMeaning: "سفید ہرنی", englishMeaning: "White gazelle", origin: "Arabic", country: "Bahrain" },

{ name: "Mohammed", gender: "boy", urduMeaning: "قابلِ تعریف", englishMeaning: "Praised, praiseworthy", origin: "Arabic", religion: "Islamic", country: "Bahrain" },
{ name: "Ahmed", gender: "boy", urduMeaning: "سب سے زیادہ قابلِ تعریف", englishMeaning: "Most praiseworthy", origin: "Arabic", religion: "Islamic", country: "Bahrain" },
{ name: "Ali", gender: "boy", urduMeaning: "بلند، عالی", englishMeaning: "High, exalted", origin: "Arabic", religion: "Islamic", country: "Bahrain" },
{ name: "Hassan", gender: "boy", urduMeaning: "خوبصورت، اچھا", englishMeaning: "Handsome, good", origin: "Arabic", religion: "Islamic", country: "Bahrain" },
{ name: "Hussein", gender: "boy", urduMeaning: "خوبصورت، نیک", englishMeaning: "Good, beautiful", origin: "Arabic", religion: "Islamic", country: "Bahrain" },
{ name: "Omar", gender: "boy", urduMeaning: "زندگی، خوشحالی", englishMeaning: "Life, flourishing", origin: "Arabic", religion: "Islamic", country: "Bahrain" },
{ name: "Yusuf", gender: "boy", urduMeaning: "اللہ اضافہ کرے", englishMeaning: "God will increase", origin: "Arabic / Hebrew", religion: "Islamic", country: "Bahrain" },
{ name: "Abdullah", gender: "boy", urduMeaning: "اللہ کا بندہ", englishMeaning: "Servant of Allah", origin: "Arabic", religion: "Islamic", country: "Bahrain" },
{ name: "Khalid", gender: "boy", urduMeaning: "ہمیشہ رہنے والا", englishMeaning: "Eternal, everlasting", origin: "Arabic", country: "Bahrain" },
{ name: "Salman", gender: "boy", urduMeaning: "محفوظ، سلامت", englishMeaning: "Safe, secure", origin: "Arabic", religion: "Islamic", country: "Bahrain" },

{ name: "Noor", gender: "both", urduMeaning: "روشنی", englishMeaning: "Light", origin: "Arabic", country: "Bahrain" },
{ name: "Iman", gender: "both", urduMeaning: "ایمان، یقین", englishMeaning: "Faith, belief", origin: "Arabic", religion: "Islamic", country: "Bahrain" },

// CYPRUS

{ name: "Maria", gender: "girl", urduMeaning: "محبوب، مریم", englishMeaning: "Beloved", origin: "Greek / Hebrew", country: "Cyprus" },
{ name: "Anna", gender: "girl", urduMeaning: "فضل، مہربانی", englishMeaning: "Grace, favor", origin: "Greek / Hebrew", country: "Cyprus" },
{ name: "Eleni", gender: "girl", urduMeaning: "روشن، چمکدار", englishMeaning: "Bright, shining", origin: "Greek", country: "Cyprus" },
{ name: "Sofia", gender: "girl", urduMeaning: "حکمت، دانائی", englishMeaning: "Wisdom", origin: "Greek", country: "Cyprus" },
{ name: "Christina", gender: "girl", urduMeaning: "مسیحی", englishMeaning: "Christian", origin: "Greek / Latin", country: "Cyprus" },
{ name: "Andriana", gender: "girl", urduMeaning: "بہادر، مضبوط", englishMeaning: "Brave, strong", origin: "Greek", country: "Cyprus" },
{ name: "Georgia", gender: "girl", urduMeaning: "کاشتکار، کسان", englishMeaning: "Farmer, earthworker", origin: "Greek", country: "Cyprus" },
{ name: "Dimitra", gender: "girl", urduMeaning: "زرخیزی سے متعلق", englishMeaning: "Devoted to Demeter", origin: "Greek", country: "Cyprus" },
{ name: "Katerina", gender: "girl", urduMeaning: "پاک، صاف", englishMeaning: "Pure", origin: "Greek", country: "Cyprus" },
{ name: "Irene", gender: "girl", urduMeaning: "امن", englishMeaning: "Peace", origin: "Greek", country: "Cyprus" },

{ name: "Andreas", gender: "boy", urduMeaning: "بہادر، مردانہ", englishMeaning: "Brave, manly", origin: "Greek", country: "Cyprus" },
{ name: "Georgios", gender: "boy", urduMeaning: "کاشتکار، کسان", englishMeaning: "Farmer, earthworker", origin: "Greek", country: "Cyprus" },
{ name: "Christos", gender: "boy", urduMeaning: "مسیح، مسح کیا ہوا", englishMeaning: "Christ, anointed", origin: "Greek", country: "Cyprus" },
{ name: "Dimitris", gender: "boy", urduMeaning: "زرخیزی سے متعلق", englishMeaning: "Devoted to Demeter", origin: "Greek", country: "Cyprus" },
{ name: "Nikos", gender: "boy", urduMeaning: "لوگوں کی فتح", englishMeaning: "Victory of the people", origin: "Greek", country: "Cyprus" },
{ name: "Constantinos", gender: "boy", urduMeaning: "مستقل، ثابت قدم", englishMeaning: "Constant, steadfast", origin: "Greek / Latin", country: "Cyprus" },
{ name: "Michael", gender: "boy", urduMeaning: "خدا کے مانند کون ہے؟", englishMeaning: "Who is like God?", origin: "Greek / Hebrew", country: "Cyprus" },
{ name: "Alexandros", gender: "boy", urduMeaning: "انسانیت کا محافظ", englishMeaning: "Defender of mankind", origin: "Greek", country: "Cyprus" },
{ name: "Panagiotis", gender: "boy", urduMeaning: "تمام مقدس", englishMeaning: "All-holy", origin: "Greek", country: "Cyprus" },
{ name: "Kyriakos", gender: "boy", urduMeaning: "رب سے متعلق", englishMeaning: "Belonging to the Lord", origin: "Greek", country: "Cyprus" },

{ name: "Alexis", gender: "both", urduMeaning: "مددگار، محافظ", englishMeaning: "Helper, defender", origin: "Greek", country: "Cyprus" },
{ name: "Niki", gender: "both", urduMeaning: "فتح", englishMeaning: "Victory", origin: "Greek", country: "Cyprus" },

// EGYPT

{ name: "Mariam", gender: "girl", urduMeaning: "پاکیزہ، عبادت گزار", englishMeaning: "Pure, devoted", origin: "Arabic / Hebrew", country: "Egypt" },
{ name: "Nour", gender: "girl", urduMeaning: "روشنی", englishMeaning: "Light", origin: "Arabic", country: "Egypt" },
{ name: "Fatma", gender: "girl", urduMeaning: "پاکیزہ، پرہیزگار", englishMeaning: "Pure, abstinent", origin: "Arabic", religion: "Islamic", country: "Egypt" },
{ name: "Aya", gender: "girl", urduMeaning: "نشانی، آیت", englishMeaning: "Sign, verse", origin: "Arabic", religion: "Islamic", country: "Egypt" },
{ name: "Hana", gender: "girl", urduMeaning: "خوشی، مسرت", englishMeaning: "Happiness, bliss", origin: "Arabic", country: "Egypt" },
{ name: "Jana", gender: "girl", urduMeaning: "جنت کا باغ", englishMeaning: "Garden of paradise", origin: "Arabic", country: "Egypt" },
{ name: "Malak", gender: "girl", urduMeaning: "فرشتہ", englishMeaning: "Angel", origin: "Arabic", country: "Egypt" },
{ name: "Salma", gender: "girl", urduMeaning: "محفوظ، سلامت", englishMeaning: "Safe, peaceful", origin: "Arabic", country: "Egypt" },
{ name: "Farah", gender: "girl", urduMeaning: "خوشی، مسرت", englishMeaning: "Joy, happiness", origin: "Arabic", country: "Egypt" },
{ name: "Rania", gender: "girl", urduMeaning: "ملکہ، دیکھنے والی", englishMeaning: "Queen; gazing", origin: "Arabic", country: "Egypt" },

{ name: "Mohamed", gender: "boy", urduMeaning: "قابلِ تعریف", englishMeaning: "Praised, praiseworthy", origin: "Arabic", religion: "Islamic", country: "Egypt" },
{ name: "Ahmed", gender: "boy", urduMeaning: "سب سے زیادہ قابلِ تعریف", englishMeaning: "Most praiseworthy", origin: "Arabic", religion: "Islamic", country: "Egypt" },
{ name: "Omar", gender: "boy", urduMeaning: "زندگی، خوشحالی", englishMeaning: "Life, flourishing", origin: "Arabic", religion: "Islamic", country: "Egypt" },
{ name: "Youssef", gender: "boy", urduMeaning: "اللہ اضافہ کرے", englishMeaning: "God will increase", origin: "Arabic / Hebrew", religion: "Islamic", country: "Egypt" },
{ name: "Abdullah", gender: "boy", urduMeaning: "اللہ کا بندہ", englishMeaning: "Servant of Allah", origin: "Arabic", religion: "Islamic", country: "Egypt" },
{ name: "Mahmoud", gender: "boy", urduMeaning: "قابلِ تعریف", englishMeaning: "Praiseworthy", origin: "Arabic", religion: "Islamic", country: "Egypt" },
{ name: "Hassan", gender: "boy", urduMeaning: "خوبصورت، اچھا", englishMeaning: "Handsome, good", origin: "Arabic", religion: "Islamic", country: "Egypt" },
{ name: "Karim", gender: "boy", urduMeaning: "سخی، معزز", englishMeaning: "Generous, noble", origin: "Arabic", country: "Egypt" },
{ name: "Khaled", gender: "boy", urduMeaning: "ہمیشہ رہنے والا", englishMeaning: "Eternal, everlasting", origin: "Arabic", country: "Egypt" },
{ name: "Mostafa", gender: "boy", urduMeaning: "منتخب کیا ہوا", englishMeaning: "Chosen, selected", origin: "Arabic", religion: "Islamic", country: "Egypt" },

{ name: "Islam", gender: "both", urduMeaning: "اللہ کے سامنے سپردگی، اسلام", englishMeaning: "Submission to God; Islam", origin: "Arabic", religion: "Islamic", country: "Egypt" },
{ name: "Nour", gender: "both", urduMeaning: "روشنی", englishMeaning: "Light", origin: "Arabic", country: "Egypt" },

// IRAN

{ name: "Fatemeh", gender: "girl", urduMeaning: "پاکیزہ، پرہیزگار", englishMeaning: "Pure, abstinent", origin: "Persian / Arabic", religion: "Islamic", country: "Iran" },
{ name: "Zahra", gender: "girl", urduMeaning: "روشن، چمکدار", englishMeaning: "Radiant, bright", origin: "Persian / Arabic", religion: "Islamic", country: "Iran" },
{ name: "Maryam", gender: "girl", urduMeaning: "پاکیزہ", englishMeaning: "Pure", origin: "Persian / Hebrew", religion: "Islamic", country: "Iran" },
{ name: "Sara", gender: "girl", urduMeaning: "شہزادی، معزز خاتون", englishMeaning: "Princess, noblewoman", origin: "Persian / Hebrew", country: "Iran" },
{ name: "Narges", gender: "girl", urduMeaning: "نرگس کا پھول", englishMeaning: "Narcissus flower", origin: "Persian", country: "Iran" },
{ name: "Parisa", gender: "girl", urduMeaning: "پری جیسی", englishMeaning: "Like a fairy", origin: "Persian", country: "Iran" },
{ name: "Mina", gender: "girl", urduMeaning: "نیلے شیشے جیسا، خوبصورت", englishMeaning: "Enamel; delicate", origin: "Persian", country: "Iran" },
{ name: "Leila", gender: "girl", urduMeaning: "رات", englishMeaning: "Night", origin: "Persian / Arabic", country: "Iran" },
{ name: "Roya", gender: "girl", urduMeaning: "خواب، رویا", englishMeaning: "Dream, vision", origin: "Persian", country: "Iran" },
{ name: "Shirin", gender: "girl", urduMeaning: "میٹھی، دلکش", englishMeaning: "Sweet, charming", origin: "Persian", country: "Iran" },

{ name: "Mohammad", gender: "boy", urduMeaning: "قابلِ تعریف", englishMeaning: "Praised, praiseworthy", origin: "Persian / Arabic", religion: "Islamic", country: "Iran" },
{ name: "Ali", gender: "boy", urduMeaning: "بلند، عالی", englishMeaning: "High, exalted", origin: "Persian / Arabic", religion: "Islamic", country: "Iran" },
{ name: "Hossein", gender: "boy", urduMeaning: "خوبصورت، نیک", englishMeaning: "Good, beautiful", origin: "Persian / Arabic", religion: "Islamic", country: "Iran" },
{ name: "Reza", gender: "boy", urduMeaning: "رضامندی، اطمینان", englishMeaning: "Contentment, satisfaction", origin: "Persian / Arabic", religion: "Islamic", country: "Iran" },
{ name: "Amir", gender: "boy", urduMeaning: "حکمران، امیر", englishMeaning: "Prince, commander", origin: "Persian / Arabic", country: "Iran" },
{ name: "Arman", gender: "boy", urduMeaning: "خواہش، آرزو", englishMeaning: "Aspiration, ideal", origin: "Persian", country: "Iran" },
{ name: "Kian", gender: "boy", urduMeaning: "بادشاہی، شاہی خاندان", englishMeaning: "Royal, kingly", origin: "Persian", country: "Iran" },
{ name: "Dariush", gender: "boy", urduMeaning: "خوشحال، دولت مند", englishMeaning: "Possessing goodness", origin: "Persian", country: "Iran" },
{ name: "Farhad", gender: "boy", urduMeaning: "خوشی، مسرت", englishMeaning: "Joyful", origin: "Persian", country: "Iran" },
{ name: "Navid", gender: "boy", urduMeaning: "خوشخبری", englishMeaning: "Good news", origin: "Persian", country: "Iran" },

{ name: "Noor", gender: "both", urduMeaning: "روشنی", englishMeaning: "Light", origin: "Persian / Arabic", country: "Iran" },
{ name: "Arian", gender: "both", urduMeaning: "آریائی، معزز", englishMeaning: "Noble, Aryan", origin: "Persian", country: "Iran" },

// IRAQ

{ name: "Fatima", gender: "girl", urduMeaning: "پاکیزہ، پرہیزگار", englishMeaning: "Pure, abstinent", origin: "Arabic", religion: "Islamic", country: "Iraq" },
{ name: "Zahra", gender: "girl", urduMeaning: "روشن، چمکدار", englishMeaning: "Radiant, bright", origin: "Arabic", religion: "Islamic", country: "Iraq" },
{ name: "Maryam", gender: "girl", urduMeaning: "پاکیزہ", englishMeaning: "Pure", origin: "Arabic / Hebrew", religion: "Islamic", country: "Iraq" },
{ name: "Zainab", gender: "girl", urduMeaning: "خوشبودار پھول", englishMeaning: "Fragrant flower", origin: "Arabic", religion: "Islamic", country: "Iraq" },
{ name: "Ruqayya", gender: "girl", urduMeaning: "بلندی، ترقی", englishMeaning: "Elevation, ascent", origin: "Arabic", religion: "Islamic", country: "Iraq" },
{ name: "Noor", gender: "girl", urduMeaning: "روشنی", englishMeaning: "Light", origin: "Arabic", country: "Iraq" },
{ name: "Huda", gender: "girl", urduMeaning: "ہدایت", englishMeaning: "Guidance", origin: "Arabic", religion: "Islamic", country: "Iraq" },
{ name: "Amal", gender: "girl", urduMeaning: "امید", englishMeaning: "Hope", origin: "Arabic", country: "Iraq" },
{ name: "Aya", gender: "girl", urduMeaning: "نشانی، آیت", englishMeaning: "Sign, verse", origin: "Arabic", religion: "Islamic", country: "Iraq" },
{ name: "Sara", gender: "girl", urduMeaning: "شہزادی، معزز خاتون", englishMeaning: "Princess, noblewoman", origin: "Arabic / Hebrew", country: "Iraq" },

{ name: "Ali", gender: "boy", urduMeaning: "بلند، عالی", englishMeaning: "High, exalted", origin: "Arabic", religion: "Islamic", country: "Iraq" },
{ name: "Hassan", gender: "boy", urduMeaning: "خوبصورت، اچھا", englishMeaning: "Handsome, good", origin: "Arabic", religion: "Islamic", country: "Iraq" },
{ name: "Hussein", gender: "boy", urduMeaning: "خوبصورت، نیک", englishMeaning: "Good, beautiful", origin: "Arabic", religion: "Islamic", country: "Iraq" },
{ name: "Mohammed", gender: "boy", urduMeaning: "قابلِ تعریف", englishMeaning: "Praised, praiseworthy", origin: "Arabic", religion: "Islamic", country: "Iraq" },
{ name: "Ahmed", gender: "boy", urduMeaning: "سب سے زیادہ قابلِ تعریف", englishMeaning: "Most praiseworthy", origin: "Arabic", religion: "Islamic", country: "Iraq" },
{ name: "Mustafa", gender: "boy", urduMeaning: "منتخب کیا ہوا", englishMeaning: "Chosen, selected", origin: "Arabic", religion: "Islamic", country: "Iraq" },
{ name: "Omar", gender: "boy", urduMeaning: "زندگی، خوشحالی", englishMeaning: "Life, flourishing", origin: "Arabic", religion: "Islamic", country: "Iraq" },
{ name: "Yusuf", gender: "boy", urduMeaning: "اللہ اضافہ کرے", englishMeaning: "God will increase", origin: "Arabic / Hebrew", religion: "Islamic", country: "Iraq" },
{ name: "Kareem", gender: "boy", urduMeaning: "سخی، معزز", englishMeaning: "Generous, noble", origin: "Arabic", country: "Iraq" },
{ name: "Haider", gender: "boy", urduMeaning: "شیر، بہادر", englishMeaning: "Lion, brave", origin: "Arabic", religion: "Islamic", country: "Iraq" },

{ name: "Noor", gender: "both", urduMeaning: "روشنی", englishMeaning: "Light", origin: "Arabic", country: "Iraq" },
{ name: "Iman", gender: "both", urduMeaning: "ایمان، یقین", englishMeaning: "Faith, belief", origin: "Arabic", religion: "Islamic", country: "Iraq" },

// ISRAEL

{ name: "Noa", gender: "girl", urduMeaning: "حرکت، سکون", englishMeaning: "Movement, motion", origin: "Hebrew", religion: "Jewish", country: "Israel" },
{ name: "Maya", gender: "girl", urduMeaning: "پانی، چشمہ", englishMeaning: "Water; spring", origin: "Hebrew / Sanskrit", country: "Israel" },
{ name: "Tamar", gender: "girl", urduMeaning: "کھجور کا درخت", englishMeaning: "Date palm", origin: "Hebrew", religion: "Jewish", country: "Israel" },
{ name: "Yael", gender: "girl", urduMeaning: "پہاڑی بکری", englishMeaning: "Mountain goat", origin: "Hebrew", religion: "Jewish", country: "Israel" },
{ name: "Shira", gender: "girl", urduMeaning: "گیت، نغمہ", englishMeaning: "Song, poetry", origin: "Hebrew", country: "Israel" },
{ name: "Avigail", gender: "girl", urduMeaning: "والد کی خوشی", englishMeaning: "Father's joy", origin: "Hebrew", religion: "Jewish", country: "Israel" },
{ name: "Michal", gender: "girl", urduMeaning: "خدا کے مانند کون ہے؟", englishMeaning: "Who is like God?", origin: "Hebrew", religion: "Jewish", country: "Israel" },
{ name: "Lior", gender: "girl", urduMeaning: "میری روشنی", englishMeaning: "My light", origin: "Hebrew", country: "Israel" },
{ name: "Hadas", gender: "girl", urduMeaning: "مورت کا درخت", englishMeaning: "Myrtle tree", origin: "Hebrew", religion: "Jewish", country: "Israel" },
{ name: "Roni", gender: "girl", urduMeaning: "میری خوشی", englishMeaning: "My joy", origin: "Hebrew", country: "Israel" },

{ name: "David", gender: "boy", urduMeaning: "محبوب", englishMeaning: "Beloved", origin: "Hebrew", religion: "Jewish", country: "Israel" },
{ name: "Daniel", gender: "boy", urduMeaning: "خدا میرا منصف ہے", englishMeaning: "God is my judge", origin: "Hebrew", religion: "Jewish", country: "Israel" },
{ name: "Noam", gender: "boy", urduMeaning: "خوشگوار، دلکش", englishMeaning: "Pleasant, pleasantness", origin: "Hebrew", country: "Israel" },
{ name: "Yosef", gender: "boy", urduMeaning: "اللہ اضافہ کرے", englishMeaning: "God will increase", origin: "Hebrew", religion: "Jewish", country: "Israel" },
{ name: "Eitan", gender: "boy", urduMeaning: "مضبوط، ثابت قدم", englishMeaning: "Strong, steadfast", origin: "Hebrew", country: "Israel" },
{ name: "Ariel", gender: "boy", urduMeaning: "خدا کا شیر", englishMeaning: "Lion of God", origin: "Hebrew", religion: "Jewish", country: "Israel" },
{ name: "Yonatan", gender: "boy", urduMeaning: "خدا نے عطا کیا", englishMeaning: "God has given", origin: "Hebrew", religion: "Jewish", country: "Israel" },
{ name: "Omer", gender: "boy", urduMeaning: "پھلوں کی فصل، خوشحال", englishMeaning: "Sheaf of grain; flourishing", origin: "Hebrew", country: "Israel" },
{ name: "Itai", gender: "boy", urduMeaning: "میرے ساتھ", englishMeaning: "With me", origin: "Hebrew", country: "Israel" },
{ name: "Uri", gender: "boy", urduMeaning: "میری روشنی", englishMeaning: "My light", origin: "Hebrew", religion: "Jewish", country: "Israel" },

{ name: "Lior", gender: "both", urduMeaning: "میری روشنی", englishMeaning: "My light", origin: "Hebrew", country: "Israel" },
{ name: "Roni", gender: "both", urduMeaning: "میری خوشی", englishMeaning: "My joy", origin: "Hebrew", country: "Israel" },



// ==================== JORDAN ====================

{ name: "Fatima", gender: "girl", urduMeaning: "پاکیزہ، پرہیزگار", englishMeaning: "Pure, one who abstains", origin: "Arabic", religion: "Islamic", country: "Jordan" },
{ name: "Mariam", gender: "girl", urduMeaning: "پاکیزہ، عبادت گزار", englishMeaning: "Pure, devoted", origin: "Arabic / Hebrew", religion: "Islamic", country: "Jordan" },
{ name: "Iman", gender: "girl", urduMeaning: "ایمان، یقین", englishMeaning: "Faith, belief", origin: "Arabic", religion: "Islamic", country: "Jordan" },
{ name: "Amal", gender: "girl", urduMeaning: "امید", englishMeaning: "Hope", origin: "Arabic", religion: "Islamic", country: "Jordan" },
{ name: "Hanan", gender: "girl", urduMeaning: "شفقت، محبت", englishMeaning: "Compassion, tenderness", origin: "Arabic", religion: "Islamic", country: "Jordan" },
{ name: "Nour", gender: "girl", urduMeaning: "روشنی", englishMeaning: "Light", origin: "Arabic", religion: "Islamic", country: "Jordan" },
{ name: "Amneh", gender: "girl", urduMeaning: "محفوظ، پُرامن", englishMeaning: "Safe, peaceful", origin: "Arabic", religion: "Islamic", country: "Jordan" },
{ name: "Abeer", gender: "girl", urduMeaning: "خوشبو، مہک", englishMeaning: "Fragrance, perfume", origin: "Arabic", religion: "Islamic", country: "Jordan" },
{ name: "Heba", gender: "girl", urduMeaning: "تحفہ، عطیہ", englishMeaning: "Gift", origin: "Arabic", religion: "Islamic", country: "Jordan" },
{ name: "Wafa", gender: "girl", urduMeaning: "وفاداری، وفا", englishMeaning: "Loyalty, faithfulness", origin: "Arabic", religion: "Islamic", country: "Jordan" },
{ name: "Manal", gender: "girl", urduMeaning: "کامیابی، حصول", englishMeaning: "Achievement, attainment", origin: "Arabic", religion: "Islamic", country: "Jordan" },
{ name: "Asmaa", gender: "girl", urduMeaning: "بلند، اعلیٰ", englishMeaning: "Exalted, lofty", origin: "Arabic", religion: "Islamic", country: "Jordan" },
{ name: "Sana", gender: "girl", urduMeaning: "چمک، شان", englishMeaning: "Radiance, brilliance", origin: "Arabic", religion: "Islamic", country: "Jordan" },
{ name: "Basma", gender: "girl", urduMeaning: "مسکراہٹ", englishMeaning: "Smile", origin: "Arabic", religion: "Islamic", country: "Jordan" },
{ name: "Nasreen", gender: "girl", urduMeaning: "جنگلی گلاب", englishMeaning: "Wild rose", origin: "Persian", religion: "Other", country: "Jordan" },
{ name: "Hoda", gender: "girl", urduMeaning: "ہدایت، رہنمائی", englishMeaning: "Guidance", origin: "Arabic", religion: "Islamic", country: "Jordan" },
{ name: "Amany", gender: "girl", urduMeaning: "خواہشات، امیدیں", englishMeaning: "Wishes, aspirations", origin: "Arabic", religion: "Islamic", country: "Jordan" },
{ name: "Duaa", gender: "girl", urduMeaning: "دعا، التجا", englishMeaning: "Prayer, supplication", origin: "Arabic", religion: "Islamic", country: "Jordan" },
{ name: "Maha", gender: "girl", urduMeaning: "خوبصورت آنکھوں والی", englishMeaning: "Beautiful eyes", origin: "Arabic", religion: "Islamic", country: "Jordan" },
{ name: "Rania", gender: "girl", urduMeaning: "دیکھنے والی، غور کرنے والی", englishMeaning: "Gazing, looking attentively", origin: "Arabic", religion: "Islamic", country: "Jordan" },

{ name: "Mohamed", gender: "boy", urduMeaning: "سب سے زیادہ تعریف کیا گیا", englishMeaning: "Most praised", origin: "Arabic", religion: "Islamic", country: "Jordan" },
{ name: "Ahmed", gender: "boy", urduMeaning: "سب سے زیادہ قابلِ تعریف", englishMeaning: "Most commendable", origin: "Arabic", religion: "Islamic", country: "Jordan" },
{ name: "Mahmoud", gender: "boy", urduMeaning: "قابلِ تعریف", englishMeaning: "Praiseworthy", origin: "Arabic", religion: "Islamic", country: "Jordan" },
{ name: "Ali", gender: "boy", urduMeaning: "بلند، اعلیٰ", englishMeaning: "High, exalted", origin: "Arabic", religion: "Islamic", country: "Jordan" },
{ name: "Khaled", gender: "boy", urduMeaning: "ہمیشہ رہنے والا", englishMeaning: "Eternal, everlasting", origin: "Arabic", religion: "Islamic", country: "Jordan" },
{ name: "Ibrahim", gender: "boy", urduMeaning: "بہت سی قوموں کا باپ", englishMeaning: "Father of many nations", origin: "Arabic / Hebrew", religion: "Islamic", country: "Jordan" },
{ name: "Omar", gender: "boy", urduMeaning: "طویل عمر والا", englishMeaning: "Long-lived", origin: "Arabic", religion: "Islamic", country: "Jordan" },
{ name: "Yousef", gender: "boy", urduMeaning: "اللہ اضافہ کرے", englishMeaning: "God increases", origin: "Arabic / Hebrew", religion: "Islamic", country: "Jordan" },
{ name: "Hassan", gender: "boy", urduMeaning: "خوبصورت، اچھا", englishMeaning: "Good, handsome", origin: "Arabic", religion: "Islamic", country: "Jordan" },
{ name: "Hussein", gender: "boy", urduMeaning: "خوبصورت، حسین", englishMeaning: "Beautiful, good", origin: "Arabic", religion: "Islamic", country: "Jordan" },
{ name: "Hamza", gender: "boy", urduMeaning: "مضبوط، بہادر", englishMeaning: "Strong, steadfast", origin: "Arabic", religion: "Islamic", country: "Jordan" },
{ name: "Mostafa", gender: "boy", urduMeaning: "منتخب کیا ہوا", englishMeaning: "The chosen one", origin: "Arabic", religion: "Islamic", country: "Jordan" },
{ name: "Osama", gender: "boy", urduMeaning: "شیر", englishMeaning: "Lion", origin: "Arabic", religion: "Islamic", country: "Jordan" },
{ name: "Suleiman", gender: "boy", urduMeaning: "پُرامن", englishMeaning: "Peaceful", origin: "Arabic / Hebrew", religion: "Islamic", country: "Jordan" },
{ name: "Ayman", gender: "boy", urduMeaning: "مبارک، خوش قسمت", englishMeaning: "Blessed, fortunate", origin: "Arabic", religion: "Islamic", country: "Jordan" },
{ name: "Tarek", gender: "boy", urduMeaning: "رات کو آنے والا، صبح کا ستارہ", englishMeaning: "Night visitor, morning star", origin: "Arabic", religion: "Islamic", country: "Jordan" },
{ name: "Waleed", gender: "boy", urduMeaning: "نوزائیدہ بچہ", englishMeaning: "Newborn child", origin: "Arabic", religion: "Islamic", country: "Jordan" },
{ name: "Anas", gender: "boy", urduMeaning: "محبت، دوستانہ پن", englishMeaning: "Affection, friendliness", origin: "Arabic", religion: "Islamic", country: "Jordan" },
{ name: "Ziad", gender: "boy", urduMeaning: "اضافہ، ترقی", englishMeaning: "Increase, growth", origin: "Arabic", religion: "Islamic", country: "Jordan" },
{ name: "Bilal", gender: "boy", urduMeaning: "تازگی، نمی", englishMeaning: "Freshness, moisture", origin: "Arabic", religion: "Islamic", country: "Jordan" },

{ name: "Nour", gender: "both", urduMeaning: "روشنی", englishMeaning: "Light", origin: "Arabic", religion: "Islamic", country: "Jordan" },
{ name: "Alaa", gender: "both", urduMeaning: "نعمتیں، بلند مرتبہ", englishMeaning: "Blessings, high status", origin: "Arabic", religion: "Islamic", country: "Jordan" },
{ name: "Jihad", gender: "both", urduMeaning: "جدوجہد، کوشش", englishMeaning: "Struggle, effort", origin: "Arabic", religion: "Islamic", country: "Jordan" },
{ name: "Anwar", gender: "both", urduMeaning: "زیادہ روشن", englishMeaning: "More radiant, brighter", origin: "Arabic", religion: "Islamic", country: "Jordan" },
{ name: "Islam", gender: "both", urduMeaning: "اسلام، امن و فرمانبرداری", englishMeaning: "Submission, peace", origin: "Arabic", religion: "Islamic", country: "Jordan" },

// ==================== KUWAIT ====================

{ name: "Fatima", gender: "girl", urduMeaning: "پاکیزہ، پرہیزگار", englishMeaning: "Pure, one who abstains", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Munira", gender: "girl", urduMeaning: "روشن، نورانی", englishMeaning: "Bright, luminous", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Mona", gender: "girl", urduMeaning: "خواہشات، تمنائیں", englishMeaning: "Wishes, desires", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Aisha", gender: "girl", urduMeaning: "زندہ، خوشحال", englishMeaning: "Alive, living", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Maryam", gender: "girl", urduMeaning: "پاکیزہ، عبادت گزار", englishMeaning: "Pure, devoted", origin: "Arabic / Hebrew", religion: "Islamic", country: "Kuwait" },
{ name: "Noura", gender: "girl", urduMeaning: "روشنی", englishMeaning: "Light", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Huda", gender: "girl", urduMeaning: "ہدایت، رہنمائی", englishMeaning: "Guidance", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Amal", gender: "girl", urduMeaning: "امید", englishMeaning: "Hope", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Hanan", gender: "girl", urduMeaning: "شفقت، محبت", englishMeaning: "Compassion, tenderness", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Rania", gender: "girl", urduMeaning: "دیکھنے والی", englishMeaning: "Gazing, looking attentively", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Maha", gender: "girl", urduMeaning: "خوبصورت آنکھوں والی", englishMeaning: "Beautiful eyes", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Farah", gender: "girl", urduMeaning: "خوشی، مسرت", englishMeaning: "Joy, happiness", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Amina", gender: "girl", urduMeaning: "قابلِ اعتماد، امانت دار", englishMeaning: "Trustworthy, faithful", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Hiba", gender: "girl", urduMeaning: "تحفہ، عطیہ", englishMeaning: "Gift", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Sara", gender: "girl", urduMeaning: "شہزادی", englishMeaning: "Princess", origin: "Hebrew / Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Reem", gender: "girl", urduMeaning: "سفید ہرن", englishMeaning: "White gazelle", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Laila", gender: "girl", urduMeaning: "رات", englishMeaning: "Night", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Yasmin", gender: "girl", urduMeaning: "چنبیلی کا پھول", englishMeaning: "Jasmine flower", origin: "Persian / Arabic", religion: "Other", country: "Kuwait" },
{ name: "Zainab", gender: "girl", urduMeaning: "خوشبودار پھول", englishMeaning: "Fragrant flower", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Khadija", gender: "girl", urduMeaning: "وقت سے پہلے پیدا ہونے والی", englishMeaning: "Early-born", origin: "Arabic", religion: "Islamic", country: "Kuwait" },

{ name: "Fahd", gender: "boy", urduMeaning: "چیتا، تیندوا", englishMeaning: "Leopard", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Badr", gender: "boy", urduMeaning: "پورا چاند", englishMeaning: "Full moon", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Hussein", gender: "boy", urduMeaning: "خوبصورت، حسین", englishMeaning: "Beautiful, good", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Mohammad", gender: "boy", urduMeaning: "سب سے زیادہ تعریف کیا گیا", englishMeaning: "Most praised", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Saud", gender: "boy", urduMeaning: "خوش بخت، خوش قسمت", englishMeaning: "Fortunate, happy", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Mubarak", gender: "boy", urduMeaning: "مبارک، بابرکت", englishMeaning: "Blessed", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Rashid", gender: "boy", urduMeaning: "ہدایت یافتہ، سمجھدار", englishMeaning: "Rightly guided, wise", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Adnan", gender: "boy", urduMeaning: "آباد رہنے والا", englishMeaning: "Settler, one who stays", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Mishal", gender: "boy", urduMeaning: "مشعل، روشنی کا ذریعہ", englishMeaning: "Torch, source of light", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Salah", gender: "boy", urduMeaning: "نیکی، درستگی", englishMeaning: "Righteousness, goodness", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Nabil", gender: "boy", urduMeaning: "شریف، معزز", englishMeaning: "Noble, honorable", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Talal", gender: "boy", urduMeaning: "خوبصورت، دلکش", englishMeaning: "Pleasant, admirable", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Abdul Aziz", gender: "boy", urduMeaning: "عزیز و غالب کا بندہ", englishMeaning: "Servant of the Almighty", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Emad", gender: "boy", urduMeaning: "سہارا، ستون", englishMeaning: "Support, pillar", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Nayef", gender: "boy", urduMeaning: "بلند، اونچا", englishMeaning: "High, elevated", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Anwar", gender: "boy", urduMeaning: "زیادہ روشن", englishMeaning: "More radiant", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Khaled", gender: "boy", urduMeaning: "ہمیشہ رہنے والا", englishMeaning: "Eternal, everlasting", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Faisal", gender: "boy", urduMeaning: "فیصلہ کرنے والا", englishMeaning: "Decisive, judge", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Saif", gender: "boy", urduMeaning: "تلوار", englishMeaning: "Sword", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Abdullah", gender: "boy", urduMeaning: "اللہ کا بندہ", englishMeaning: "Servant of Allah", origin: "Arabic", religion: "Islamic", country: "Kuwait" },

{ name: "Noor", gender: "both", urduMeaning: "روشنی", englishMeaning: "Light", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Iman", gender: "both", urduMeaning: "ایمان، یقین", englishMeaning: "Faith, belief", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Islam", gender: "both", urduMeaning: "اسلام، فرمانبرداری", englishMeaning: "Submission, peace", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Anwar", gender: "both", urduMeaning: "زیادہ روشن", englishMeaning: "More radiant", origin: "Arabic", religion: "Islamic", country: "Kuwait" },
{ name: "Amal", gender: "both", urduMeaning: "امید", englishMeaning: "Hope", origin: "Arabic", religion: "Islamic", country: "Kuwait" },


// ==================== LEBANON ====================

{ name: "Fatima", gender: "girl", urduMeaning: "پاکیزہ، پرہیزگار", englishMeaning: "Pure, one who abstains", origin: "Arabic", religion: "Islamic", country: "Lebanon" },
{ name: "Zainab", gender: "girl", urduMeaning: "خوشبودار پھول", englishMeaning: "Fragrant flower", origin: "Arabic", religion: "Islamic", country: "Lebanon" },
{ name: "Mariam", gender: "girl", urduMeaning: "پاکیزہ، عبادت گزار", englishMeaning: "Pure, devoted", origin: "Arabic / Hebrew", religion: "Islamic", country: "Lebanon" },
{ name: "Laila", gender: "girl", urduMeaning: "رات", englishMeaning: "Night", origin: "Arabic", religion: "Islamic", country: "Lebanon" },
{ name: "Mona", gender: "girl", urduMeaning: "خواہشات، تمنائیں", englishMeaning: "Wishes, desires", origin: "Arabic", religion: "Islamic", country: "Lebanon" },
{ name: "Amal", gender: "girl", urduMeaning: "امید", englishMeaning: "Hope", origin: "Arabic", religion: "Islamic", country: "Lebanon" },
{ name: "Nada", gender: "girl", urduMeaning: "شبنم، سخاوت", englishMeaning: "Dew, generosity", origin: "Arabic", religion: "Islamic", country: "Lebanon" },
{ name: "Hoda", gender: "girl", urduMeaning: "ہدایت، رہنمائی", englishMeaning: "Guidance", origin: "Arabic", religion: "Islamic", country: "Lebanon" },
{ name: "Samira", gender: "girl", urduMeaning: "رات کی ساتھی", englishMeaning: "Evening companion", origin: "Arabic", religion: "Islamic", country: "Lebanon" },
{ name: "Rima", gender: "girl", urduMeaning: "سفید ہرن", englishMeaning: "White antelope", origin: "Arabic", religion: "Other", country: "Lebanon" },
{ name: "Nadia", gender: "girl", urduMeaning: "نرم، امید سے بھرپور", englishMeaning: "Tender, hopeful", origin: "Arabic / Slavic", religion: "Other", country: "Lebanon" },
{ name: "Rania", gender: "girl", urduMeaning: "غور سے دیکھنے والی", englishMeaning: "Gazing, looking attentively", origin: "Arabic", religion: "Islamic", country: "Lebanon" },
{ name: "Rana", gender: "girl", urduMeaning: "خوبصورت، دلکش", englishMeaning: "Beautiful, charming", origin: "Arabic", religion: "Other", country: "Lebanon" },
{ name: "Rola", gender: "girl", urduMeaning: "خوبصورت عورت", englishMeaning: "Beautiful woman", origin: "Arabic", religion: "Other", country: "Lebanon" },
{ name: "Wafa", gender: "girl", urduMeaning: "وفاداری", englishMeaning: "Loyalty, faithfulness", origin: "Arabic", religion: "Islamic", country: "Lebanon" },
{ name: "Hanan", gender: "girl", urduMeaning: "شفقت، محبت", englishMeaning: "Compassion, tenderness", origin: "Arabic", religion: "Islamic", country: "Lebanon" },
{ name: "Ghada", gender: "girl", urduMeaning: "خوبصورت، نازک", englishMeaning: "Graceful, beautiful", origin: "Arabic", religion: "Islamic", country: "Lebanon" },
{ name: "Hala", gender: "girl", urduMeaning: "چاند کے گرد ہالہ", englishMeaning: "Halo around the moon", origin: "Arabic", religion: "Islamic", country: "Lebanon" },
{ name: "Abeer", gender: "girl", urduMeaning: "خوشبو، مہک", englishMeaning: "Fragrance", origin: "Arabic", religion: "Islamic", country: "Lebanon" },
{ name: "Zahra", gender: "girl", urduMeaning: "روشن، پھول", englishMeaning: "Radiant, flower", origin: "Arabic", religion: "Islamic", country: "Lebanon" },

{ name: "Mohamed", gender: "boy", urduMeaning: "سب سے زیادہ تعریف کیا گیا", englishMeaning: "Most praised", origin: "Arabic", religion: "Islamic", country: "Lebanon" },
{ name: "Ali", gender: "boy", urduMeaning: "بلند، اعلیٰ", englishMeaning: "High, exalted", origin: "Arabic", religion: "Islamic", country: "Lebanon" },
{ name: "Ahmed", gender: "boy", urduMeaning: "سب سے زیادہ قابلِ تعریف", englishMeaning: "Most commendable", origin: "Arabic", religion: "Islamic", country: "Lebanon" },
{ name: "Hassan", gender: "boy", urduMeaning: "خوبصورت، اچھا", englishMeaning: "Good, handsome", origin: "Arabic", religion: "Islamic", country: "Lebanon" },
{ name: "Hussein", gender: "boy", urduMeaning: "خوبصورت، حسین", englishMeaning: "Beautiful, good", origin: "Arabic", religion: "Islamic", country: "Lebanon" },
{ name: "Yousef", gender: "boy", urduMeaning: "اللہ اضافہ کرے", englishMeaning: "God increases", origin: "Arabic / Hebrew", religion: "Islamic", country: "Lebanon" },
{ name: "Ibrahim", gender: "boy", urduMeaning: "بہت سی قوموں کا باپ", englishMeaning: "Father of many nations", origin: "Arabic / Hebrew", religion: "Islamic", country: "Lebanon" },
{ name: "Mahmoud", gender: "boy", urduMeaning: "قابلِ تعریف", englishMeaning: "Praiseworthy", origin: "Arabic", religion: "Islamic", country: "Lebanon" },
{ name: "Khaled", gender: "boy", urduMeaning: "ہمیشہ رہنے والا", englishMeaning: "Eternal, everlasting", origin: "Arabic", religion: "Islamic", country: "Lebanon" },
{ name: "Mostafa", gender: "boy", urduMeaning: "منتخب کیا ہوا", englishMeaning: "The chosen one", origin: "Arabic", religion: "Islamic", country: "Lebanon" },
{ name: "Fadi", gender: "boy", urduMeaning: "نجات دینے والا", englishMeaning: "Redeemer, savior", origin: "Arabic", religion: "Other", country: "Lebanon" },
{ name: "Charbel", gender: "boy", urduMeaning: "عیسائی نام، مقدس نام", englishMeaning: "Christian given name", origin: "Aramaic", religion: "Christian", country: "Lebanon" },
{ name: "Antoine", gender: "boy", urduMeaning: "قابلِ تعریف، قیمتی", englishMeaning: "Priceless, praiseworthy", origin: "Greek / Latin", religion: "Christian", country: "Lebanon" },
{ name: "Michel", gender: "boy", urduMeaning: "خدا کے مانند کون؟", englishMeaning: "Who is like God?", origin: "Hebrew", religion: "Christian", country: "Lebanon" },
{ name: "Elias", gender: "boy", urduMeaning: "میرا خدا اللہ ہے", englishMeaning: "My God is Yahweh", origin: "Hebrew / Arabic", religion: "Christian", country: "Lebanon" },
{ name: "George", gender: "boy", urduMeaning: "کسان، زمین کا کاشتکار", englishMeaning: "Farmer, earthworker", origin: "Greek", religion: "Christian", country: "Lebanon" },
{ name: "Samir", gender: "boy", urduMeaning: "رات کی گفتگو کا ساتھی", englishMeaning: "Evening companion", origin: "Arabic", religion: "Islamic", country: "Lebanon" },
{ name: "Waleed", gender: "boy", urduMeaning: "نوزائیدہ بچہ", englishMeaning: "Newborn child", origin: "Arabic", religion: "Islamic", country: "Lebanon" },
{ name: "Nabil", gender: "boy", urduMeaning: "شریف، معزز", englishMeaning: "Noble, honorable", origin: "Arabic", religion: "Islamic", country: "Lebanon" },
{ name: "Bilal", gender: "boy", urduMeaning: "تازگی، نمی", englishMeaning: "Freshness, moisture", origin: "Arabic", religion: "Islamic", country: "Lebanon" },

{ name: "Nour", gender: "both", urduMeaning: "روشنی", englishMeaning: "Light", origin: "Arabic", religion: "Islamic", country: "Lebanon" },
{ name: "Iman", gender: "both", urduMeaning: "ایمان، یقین", englishMeaning: "Faith, belief", origin: "Arabic", religion: "Islamic", country: "Lebanon" },
{ name: "Jihad", gender: "both", urduMeaning: "جدوجہد، کوشش", englishMeaning: "Struggle, effort", origin: "Arabic", religion: "Islamic", country: "Lebanon" },
{ name: "Wissam", gender: "both", urduMeaning: "تمغہ، اعزاز", englishMeaning: "Medal, honor", origin: "Arabic", religion: "Other", country: "Lebanon" },
{ name: "Jamal", gender: "both", urduMeaning: "خوبصورتی", englishMeaning: "Beauty", origin: "Arabic", religion: "Islamic", country: "Lebanon" },

// ==================== OMAN ====================

{ name: "Fatima", gender: "girl", urduMeaning: "پاکیزہ، پرہیزگار", englishMeaning: "Pure, one who abstains", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Ayesha", gender: "girl", urduMeaning: "زندہ، خوشحال", englishMeaning: "Alive, living", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Zainab", gender: "girl", urduMeaning: "خوشبودار پھول", englishMeaning: "Fragrant flower", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Jamila", gender: "girl", urduMeaning: "خوبصورت", englishMeaning: "Beautiful", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Rahma", gender: "girl", urduMeaning: "رحمت، مہربانی", englishMeaning: "Mercy, compassion", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Amna", gender: "girl", urduMeaning: "محفوظ، پُرامن", englishMeaning: "Safe, peaceful", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Samia", gender: "girl", urduMeaning: "بلند، اعلیٰ", englishMeaning: "Elevated, high", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Salma", gender: "girl", urduMeaning: "پُرامن، محفوظ", englishMeaning: "Peaceful, safe", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Badriyah", gender: "girl", urduMeaning: "پورے چاند جیسی", englishMeaning: "Like the full moon", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Halima", gender: "girl", urduMeaning: "بردبار، نرم مزاج", englishMeaning: "Gentle, patient", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Alia", gender: "girl", urduMeaning: "بلند، اعلیٰ", englishMeaning: "High, exalted", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Raya", gender: "girl", urduMeaning: "خوبصورت، خوشنما", englishMeaning: "Graceful, beautiful", origin: "Arabic", religion: "Other", country: "Oman" },
{ name: "Bushra", gender: "girl", urduMeaning: "خوشخبری", englishMeaning: "Good news", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Munira", gender: "girl", urduMeaning: "روشن، نورانی", englishMeaning: "Bright, luminous", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Aida", gender: "girl", urduMeaning: "واپس آنے والی، فائدہ مند", englishMeaning: "Returning, beneficial", origin: "Arabic / Italian", religion: "Other", country: "Oman" },
{ name: "Aminah", gender: "girl", urduMeaning: "قابلِ اعتماد، امانت دار", englishMeaning: "Trustworthy, faithful", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Najma", gender: "girl", urduMeaning: "ستارہ", englishMeaning: "Star", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Asma", gender: "girl", urduMeaning: "بلند، اعلیٰ", englishMeaning: "Exalted, lofty", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Laila", gender: "girl", urduMeaning: "رات", englishMeaning: "Night", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Hana", gender: "girl", urduMeaning: "خوشی، مسرت", englishMeaning: "Happiness, bliss", origin: "Arabic", religion: "Islamic", country: "Oman" },

{ name: "Sultan", gender: "boy", urduMeaning: "حاکم، اقتدار", englishMeaning: "Ruler, authority", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Saif", gender: "boy", urduMeaning: "تلوار", englishMeaning: "Sword", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Rashid", gender: "boy", urduMeaning: "ہدایت یافتہ، سمجھدار", englishMeaning: "Rightly guided, wise", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Faisal", gender: "boy", urduMeaning: "فیصلہ کرنے والا", englishMeaning: "Decisive, judge", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Mohammed", gender: "boy", urduMeaning: "سب سے زیادہ تعریف کیا گیا", englishMeaning: "Most praised", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Ahmed", gender: "boy", urduMeaning: "سب سے زیادہ قابلِ تعریف", englishMeaning: "Most commendable", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Younis", gender: "boy", urduMeaning: "کبوتر، نبی یونس کا نام", englishMeaning: "Dove; name of Prophet Yunus", origin: "Arabic / Hebrew", religion: "Islamic", country: "Oman" },
{ name: "Khalid", gender: "boy", urduMeaning: "ہمیشہ رہنے والا", englishMeaning: "Eternal, everlasting", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Khalil", gender: "boy", urduMeaning: "قریبی دوست", englishMeaning: "Close friend", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Samir", gender: "boy", urduMeaning: "رات کی گفتگو کا ساتھی", englishMeaning: "Evening companion", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Ali", gender: "boy", urduMeaning: "بلند، اعلیٰ", englishMeaning: "High, exalted", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Jamal", gender: "boy", urduMeaning: "خوبصورتی", englishMeaning: "Beauty", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Salim", gender: "boy", urduMeaning: "محفوظ، سلامت", englishMeaning: "Safe, sound", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Abdullah", gender: "boy", urduMeaning: "اللہ کا بندہ", englishMeaning: "Servant of Allah", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Adnan", gender: "boy", urduMeaning: "آباد رہنے والا", englishMeaning: "Settler, one who stays", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Tariq", gender: "boy", urduMeaning: "رات کو آنے والا، ستارہ", englishMeaning: "Night visitor, morning star", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Said", gender: "boy", urduMeaning: "خوش، خوش قسمت", englishMeaning: "Happy, fortunate", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Habib", gender: "boy", urduMeaning: "محبوب، پیارا", englishMeaning: "Beloved, dear", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Nasser", gender: "boy", urduMeaning: "مدد کرنے والا، فاتح", englishMeaning: "Helper, victor", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Saeed", gender: "boy", urduMeaning: "خوش قسمت، خوش", englishMeaning: "Happy, fortunate", origin: "Arabic", religion: "Islamic", country: "Oman" },

{ name: "Anwar", gender: "both", urduMeaning: "زیادہ روشن", englishMeaning: "More radiant", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Shams", gender: "both", urduMeaning: "سورج", englishMeaning: "Sun", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Iman", gender: "both", urduMeaning: "ایمان، یقین", englishMeaning: "Faith, belief", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Noor", gender: "both", urduMeaning: "روشنی", englishMeaning: "Light", origin: "Arabic", religion: "Islamic", country: "Oman" },
{ name: "Amal", gender: "both", urduMeaning: "امید", englishMeaning: "Hope", origin: "Arabic", religion: "Islamic", country: "Oman" },

// ==================== PALESTINE ====================

{ name: "Fatima", gender: "girl", urduMeaning: "پاکیزہ، پرہیزگار", englishMeaning: "Pure, one who abstains", origin: "Arabic", religion: "Islamic", country: "Palestine" },
{ name: "Mariam", gender: "girl", urduMeaning: "پاکیزہ، عبادت گزار", englishMeaning: "Pure, devoted", origin: "Arabic / Hebrew", religion: "Islamic", country: "Palestine" },
{ name: "Iman", gender: "girl", urduMeaning: "ایمان، یقین", englishMeaning: "Faith, belief", origin: "Arabic", religion: "Islamic", country: "Palestine" },
{ name: "Amal", gender: "girl", urduMeaning: "امید", englishMeaning: "Hope", origin: "Arabic", religion: "Islamic", country: "Palestine" },
{ name: "Amneh", gender: "girl", urduMeaning: "محفوظ، پُرامن", englishMeaning: "Safe, peaceful", origin: "Arabic", religion: "Islamic", country: "Palestine" },
{ name: "Hanan", gender: "girl", urduMeaning: "شفقت، محبت", englishMeaning: "Compassion, tenderness", origin: "Arabic", religion: "Islamic", country: "Palestine" },
{ name: "Mona", gender: "girl", urduMeaning: "خواہشات، تمنائیں", englishMeaning: "Wishes, desires", origin: "Arabic", religion: "Islamic", country: "Palestine" },
{ name: "Manal", gender: "girl", urduMeaning: "کامیابی، حصول", englishMeaning: "Achievement, attainment", origin: "Arabic", religion: "Islamic", country: "Palestine" },
{ name: "Nasreen", gender: "girl", urduMeaning: "جنگلی گلاب", englishMeaning: "Wild rose", origin: "Persian", religion: "Other", country: "Palestine" },
{ name: "Abeer", gender: "girl", urduMeaning: "خوشبو، مہک", englishMeaning: "Fragrance", origin: "Arabic", religion: "Islamic", country: "Palestine" },
{ name: "Sana", gender: "girl", urduMeaning: "چمک، شان", englishMeaning: "Radiance, brilliance", origin: "Arabic", religion: "Islamic", country: "Palestine" },
{ name: "Samira", gender: "girl", urduMeaning: "رات کی ساتھی", englishMeaning: "Evening companion", origin: "Arabic", religion: "Islamic", country: "Palestine" },
{ name: "Asmaa", gender: "girl", urduMeaning: "بلند، اعلیٰ", englishMeaning: "Exalted, lofty", origin: "Arabic", religion: "Islamic", country: "Palestine" },
{ name: "Jamila", gender: "girl", urduMeaning: "خوبصورت", englishMeaning: "Beautiful", origin: "Arabic", religion: "Islamic", country: "Palestine" },
{ name: "Heba", gender: "girl", urduMeaning: "تحفہ، عطیہ", englishMeaning: "Gift", origin: "Arabic", religion: "Islamic", country: "Palestine" },
{ name: "Halima", gender: "girl", urduMeaning: "بردبار، نرم مزاج", englishMeaning: "Gentle, patient", origin: "Arabic", religion: "Islamic", country: "Palestine" },
{ name: "Ibtisam", gender: "girl", urduMeaning: "مسکراہٹ", englishMeaning: "Smile", origin: "Arabic", religion: "Islamic", country: "Palestine" },
{ name: "Souad", gender: "girl", urduMeaning: "خوشی، خوش بختی", englishMeaning: "Happiness, good fortune", origin: "Arabic", religion: "Islamic", country: "Palestine" },
{ name: "Siham", gender: "girl", urduMeaning: "تیر، تیر انداز کے تیر", englishMeaning: "Arrows", origin: "Arabic", religion: "Islamic", country: "Palestine" },
{ name: "Basma", gender: "girl", urduMeaning: "مسکراہٹ", englishMeaning: "Smile", origin: "Arabic", religion: "Islamic", country: "Palestine" },

{ name: "Mohamed", gender: "boy", urduMeaning: "سب سے زیادہ تعریف کیا گیا", englishMeaning: "Most praised", origin: "Arabic", religion: "Islamic", country: "Palestine" },
{ name: "Ahmed", gender: "boy", urduMeaning: "سب سے زیادہ قابلِ تعریف", englishMeaning: "Most commendable", origin: "Arabic", religion: "Islamic", country: "Palestine" },
{ name: "Mahmoud", gender: "boy", urduMeaning: "قابلِ تعریف", englishMeaning: "Praiseworthy", origin: "Arabic", religion: "Islamic", country: "Palestine" },
{ name: "Ibrahim", gender: "boy", urduMeaning: "بہت سی قوموں کا باپ", englishMeaning: "Father of many nations", origin: "Arabic / Hebrew", religion: "Islamic", country: "Palestine" },
{ name: "Khaled", gender: "boy", urduMeaning: "ہمیشہ رہنے والا", englishMeaning: "Eternal, everlasting", origin: "Arabic", religion: "Islamic", country: "Palestine" },
{ name: "Ali", gender: "boy", urduMeaning: "بلند، اعلیٰ", englishMeaning: "High, exalted", origin: "Arabic", religion: "Islamic", country: "Palestine" },
{ name: "Yousef", gender: "boy", urduMeaning: "اللہ اضافہ کرے", englishMeaning: "God increases", origin: "Arabic / Hebrew", religion: "Islamic", country: "Palestine" },
{ name: "Hassan", gender: "boy", urduMeaning: "خوبصورت، اچھا", englishMeaning: "Good, handsome", origin: "Arabic", religion: "Islamic", country: "Palestine" },
{ name: "Raed", gender: "boy", urduMeaning: "رہنما، قائد", englishMeaning: "Leader, pioneer", origin: "Arabic", religion: "Islamic", country: "Palestine" },
{ name: "Emad", gender: "boy", urduMeaning: "سہارا، ستون", englishMeaning: "Support, pillar", origin: "Arabic", religion: "Islamic", country: "Palestine" },
{ name: "Iyad", gender: "boy", urduMeaning: "طاقت، مدد", englishMeaning: "Strength, support", origin: "Arabic", religion: "Islamic", country: "Palestine" },
{ name: "Omar", gender: "boy", urduMeaning: "طویل عمر والا", englishMeaning: "Long-lived", origin: "Arabic", religion: "Islamic", country: "Palestine" },
{ name: "Jamal", gender: "boy", urduMeaning: "خوبصورتی", englishMeaning: "Beauty", origin: "Arabic", religion: "Islamic", country: "Palestine" },
{ name: "Khalil", gender: "boy", urduMeaning: "قریبی دوست", englishMeaning: "Close friend", origin: "Arabic", religion: "Islamic", country: "Palestine" },
{ name: "Ayman", gender: "boy", urduMeaning: "مبارک، خوش قسمت", englishMeaning: "Blessed, fortunate", origin: "Arabic", religion: "Islamic", country: "Palestine" },
{ name: "Ramy", gender: "boy", urduMeaning: "تیر انداز", englishMeaning: "Archer", origin: "Arabic", religion: "Islamic", country: "Palestine" },
{ name: "Ismail", gender: "boy", urduMeaning: "اللہ سنتا ہے", englishMeaning: "God hears", origin: "Arabic / Hebrew", religion: "Islamic", country: "Palestine" },
{ name: "Abdullah", gender: "boy", urduMeaning: "اللہ کا بندہ", englishMeaning: "Servant of Allah", origin: "Arabic", religion: "Islamic", country: "Palestine" },
{ name: "Ziad", gender: "boy", urduMeaning: "اضافہ، ترقی", englishMeaning: "Increase, growth", origin: "Arabic", religion: "Islamic", country: "Palestine" },
{ name: "Osama", gender: "boy", urduMeaning: "شیر", englishMeaning: "Lion", origin: "Arabic", religion: "Islamic", country: "Palestine" },

{ name: "Alaa", gender: "both", urduMeaning: "نعمتیں، بلند مرتبہ", englishMeaning: "Blessings, high status", origin: "Arabic", religion: "Islamic", country: "Palestine" },
{ name: "Jihad", gender: "both", urduMeaning: "جدوجہد، کوشش", englishMeaning: "Struggle, effort", origin: "Arabic", religion: "Islamic", country: "Palestine" },
{ name: "Nour", gender: "both", urduMeaning: "روشنی", englishMeaning: "Light", origin: "Arabic", religion: "Islamic", country: "Palestine" },
{ name: "Anwar", gender: "both", urduMeaning: "زیادہ روشن", englishMeaning: "More radiant", origin: "Arabic", religion: "Islamic", country: "Palestine" },
{ name: "Wafa", gender: "both", urduMeaning: "وفاداری", englishMeaning: "Loyalty, faithfulness", origin: "Arabic", religion: "Islamic", country: "Palestine" },

// ==================== QATAR ====================

{ name: "Sara", gender: "girl", urduMeaning: "شہزادی", englishMeaning: "Princess", origin: "Arabic / Hebrew", religion: "Islamic", country: "Qatar" },
{ name: "Marwa", gender: "girl", urduMeaning: "مروہ کا پتھر، مضبوط", englishMeaning: "Marwah stone, strong", origin: "Arabic", religion: "Islamic", country: "Qatar" },
{ name: "Rima", gender: "girl", urduMeaning: "سفید ہرن", englishMeaning: "White gazelle", origin: "Arabic", religion: "Islamic", country: "Qatar" },
{ name: "Noura", gender: "girl", urduMeaning: "روشنی", englishMeaning: "Light", origin: "Arabic", religion: "Islamic", country: "Qatar" },
{ name: "Aisha", gender: "girl", urduMeaning: "زندہ، خوشحال", englishMeaning: "Alive, living", origin: "Arabic", religion: "Islamic", country: "Qatar" },
{ name: "Fatima", gender: "girl", urduMeaning: "پاکیزہ، پرہیزگار", englishMeaning: "Pure, one who abstains", origin: "Arabic", religion: "Islamic", country: "Qatar" },
{ name: "Maryam", gender: "girl", urduMeaning: "پاکیزہ، عبادت گزار", englishMeaning: "Pure, devoted", origin: "Arabic / Hebrew", religion: "Islamic", country: "Qatar" },
{ name: "Huda", gender: "girl", urduMeaning: "ہدایت، رہنمائی", englishMeaning: "Guidance", origin: "Arabic", religion: "Islamic", country: "Qatar" },
{ name: "Amal", gender: "girl", urduMeaning: "امید", englishMeaning: "Hope", origin: "Arabic", religion: "Islamic", country: "Qatar" },
{ name: "Hanan", gender: "girl", urduMeaning: "شفقت، محبت", englishMeaning: "Compassion, tenderness", origin: "Arabic", religion: "Islamic", country: "Qatar" },
{ name: "Maha", gender: "girl", urduMeaning: "خوبصورت آنکھوں والی", englishMeaning: "Beautiful eyes", origin: "Arabic", religion: "Islamic", country: "Qatar" },
{ name: "Reem", gender: "girl", urduMeaning: "سفید ہرن", englishMeaning: "White gazelle", origin: "Arabic", religion: "Islamic", country: "Qatar" },
{ name: "Heba", gender: "girl", urduMeaning: "تحفہ، عطیہ", englishMeaning: "Gift", origin: "Arabic", religion: "Islamic", country: "Qatar" },
{ name: "Amina", gender: "girl", urduMeaning: "قابلِ اعتماد، امانت دار", englishMeaning: "Trustworthy, faithful", origin: "Arabic", religion: "Islamic", country: "Qatar" },
{ name: "Zainab", gender: "girl", urduMeaning: "خوشبودار پھول", englishMeaning: "Fragrant flower", origin: "Arabic", religion: "Islamic", country: "Qatar" },
{ name: "Lulwa", gender: "girl", urduMeaning: "موتی", englishMeaning: "Pearl", origin: "Arabic", religion: "Islamic", country: "Qatar" },
{ name: "Noor", gender: "girl", urduMeaning: "روشنی", englishMeaning: "Light", origin: "Arabic", religion: "Islamic", country: "Qatar" },
{ name: "Ghada", gender: "girl", urduMeaning: "خوبصورت، نازک", englishMeaning: "Graceful, beautiful", origin: "Arabic", religion: "Islamic", country: "Qatar" },
{ name: "Manal", gender: "girl", urduMeaning: "کامیابی، حصول", englishMeaning: "Achievement, attainment", origin: "Arabic", religion: "Islamic", country: "Qatar" },
{ name: "Wafa", gender: "girl", urduMeaning: "وفاداری", englishMeaning: "Loyalty, faithfulness", origin: "Arabic", religion: "Islamic", country: "Qatar" },

{ name: "Fahad", gender: "boy", urduMeaning: "چیتا، تیندوا", englishMeaning: "Leopard", origin: "Arabic", religion: "Islamic", country: "Qatar" },
{ name: "Jassim", gender: "boy", urduMeaning: "طاقتور، مضبوط", englishMeaning: "Strong, powerful", origin: "Arabic", religion: "Islamic", country: "Qatar" },
{ name: "Abdulrahman", gender: "boy", urduMeaning: "رحمٰن کا بندہ", englishMeaning: "Servant of the Most Merciful", origin: "Arabic", religion: "Islamic", country: "Qatar" },
{ name: "Salim", gender: "boy", urduMeaning: "محفوظ، سلامت", englishMeaning: "Safe, sound", origin: "Arabic", religion: "Islamic", country: "Qatar" },
{ name: "Mubarak", gender: "boy", urduMeaning: "مبارک، بابرکت", englishMeaning: "Blessed", origin: "Arabic", religion: "Islamic", country: "Qatar" },
{ name: "Faisal", gender: "boy", urduMeaning: "فیصلہ کرنے والا", englishMeaning: "Decisive, judge", origin: "Arabic", religion: "Islamic", country: "Qatar" },
{ name: "Saoud", gender: "boy", urduMeaning: "خوش بخت، خوش قسمت", englishMeaning: "Fortunate, happy", origin: "Arabic", religion: "Islamic", country: "Qatar" },
{ name: "Omer", gender: "boy", urduMeaning: "طویل عمر والا", englishMeaning: "Long-lived", origin: "Arabic", religion: "Islamic", country: "Qatar" },
{ name: "Sameh", gender: "boy", urduMeaning: "معاف کرنے والا، فیاض", englishMeaning: "Forgiving, generous", origin: "Arabic", religion: "Islamic", country: "Qatar" },
{ name: "Arshad", gender: "boy", urduMeaning: "زیادہ ہدایت یافتہ", englishMeaning: "Better guided, wiser", origin: "Arabic", religion: "Islamic", country: "Qatar" },
{ name: "Basheer", gender: "boy", urduMeaning: "خوشخبری دینے والا", englishMeaning: "Bearer of good news", origin: "Arabic", religion: "Islamic", country: "Qatar" },
{ name: "Salman", gender: "boy", urduMeaning: "محفوظ، پُرامن", englishMeaning: "Safe, peaceful", origin: "Arabic", religion: "Islamic", country: "Qatar" },
{ name: "Tamer", gender: "boy", urduMeaning: "کھجور والا، پھلدار", englishMeaning: "Date-palm owner, fruitful", origin: "Arabic", religion: "Islamic", country: "Qatar" },
{ name: "Irshad", gender: "boy", urduMeaning: "رہنمائی، ہدایت", englishMeaning: "Guidance, direction", origin: "Arabic", religion: "Islamic", country: "Qatar" },
{ name: "Yousuf", gender: "boy", urduMeaning: "اللہ اضافہ کرے", englishMeaning: "God increases", origin: "Arabic / Hebrew", religion: "Islamic", country: "Qatar" },
{ name: "Anas", gender: "boy", urduMeaning: "محبت، دوستانہ پن", englishMeaning: "Affection, friendliness", origin: "Arabic", religion: "Islamic", country: "Qatar" },
{ name: "Sulaiman", gender: "boy", urduMeaning: "پُرامن", englishMeaning: "Peaceful", origin: "Arabic / Hebrew", religion: "Islamic", country: "Qatar" },
{ name: "Thani", gender: "boy", urduMeaning: "دوسرا", englishMeaning: "Second", origin: "Arabic", religion: "Islamic", country: "Qatar" },
{ name: "Malik", gender: "boy", urduMeaning: "بادشاہ، مالک", englishMeaning: "King, owner", origin: "Arabic", religion: "Islamic", country: "Qatar" },
{ name: "Fazal", gender: "boy", urduMeaning: "فضل، مہربانی", englishMeaning: "Grace, favor", origin: "Arabic", religion: "Islamic", country: "Qatar" },

{ name: "Nur", gender: "both", urduMeaning: "روشنی", englishMeaning: "Light", origin: "Arabic", religion: "Islamic", country: "Qatar" },
{ name: "Saman", gender: "both", urduMeaning: "قیمتی، خوبصورت", englishMeaning: "Precious, beautiful", origin: "Persian / Arabic", religion: "Other", country: "Qatar" },
{ name: "Reda", gender: "both", urduMeaning: "رضامندی، اطمینان", englishMeaning: "Contentment, satisfaction", origin: "Arabic", religion: "Islamic", country: "Qatar" },
{ name: "Iman", gender: "both", urduMeaning: "ایمان، یقین", englishMeaning: "Faith, belief", origin: "Arabic", religion: "Islamic", country: "Qatar" },
{ name: "Amal", gender: "both", urduMeaning: "امید", englishMeaning: "Hope", origin: "Arabic", religion: "Islamic", country: "Qatar" },

// ==================== SAUDI ARABIA ====================

{ name: "Fatimah", gender: "girl", urduMeaning: "پاکیزہ، پرہیزگار", englishMeaning: "Pure, one who abstains", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Aisha", gender: "girl", urduMeaning: "زندہ، خوشحال", englishMeaning: "Alive, living", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Maryam", gender: "girl", urduMeaning: "پاکیزہ، عبادت گزار", englishMeaning: "Pure, devoted", origin: "Arabic / Hebrew", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Noura", gender: "girl", urduMeaning: "روشنی", englishMeaning: "Light", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Huda", gender: "girl", urduMeaning: "ہدایت، رہنمائی", englishMeaning: "Guidance", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Amal", gender: "girl", urduMeaning: "امید", englishMeaning: "Hope", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Hanan", gender: "girl", urduMeaning: "شفقت، محبت", englishMeaning: "Compassion, tenderness", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Reem", gender: "girl", urduMeaning: "سفید ہرن", englishMeaning: "White gazelle", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Maha", gender: "girl", urduMeaning: "خوبصورت آنکھوں والی", englishMeaning: "Beautiful eyes", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Rania", gender: "girl", urduMeaning: "غور سے دیکھنے والی", englishMeaning: "Gazing, looking attentively", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Sara", gender: "girl", urduMeaning: "شہزادی", englishMeaning: "Princess", origin: "Arabic / Hebrew", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Layan", gender: "girl", urduMeaning: "نرمی، آسائش", englishMeaning: "Softness, comfort", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Lama", gender: "girl", urduMeaning: "خوبصورت ہونٹوں والی", englishMeaning: "Beautiful lips", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Ghada", gender: "girl", urduMeaning: "خوبصورت، نازک", englishMeaning: "Graceful, beautiful", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Jawaher", gender: "girl", urduMeaning: "جواہرات", englishMeaning: "Jewels, precious stones", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Basma", gender: "girl", urduMeaning: "مسکراہٹ", englishMeaning: "Smile", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Abeer", gender: "girl", urduMeaning: "خوشبو، مہک", englishMeaning: "Fragrance", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Wafa", gender: "girl", urduMeaning: "وفاداری", englishMeaning: "Loyalty, faithfulness", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Zainab", gender: "girl", urduMeaning: "خوشبودار پھول", englishMeaning: "Fragrant flower", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Nawal", gender: "girl", urduMeaning: "تحفہ، عطیہ", englishMeaning: "Gift, blessing", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },

{ name: "Mohammed", gender: "boy", urduMeaning: "سب سے زیادہ تعریف کیا گیا", englishMeaning: "Most praised", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Abdullah", gender: "boy", urduMeaning: "اللہ کا بندہ", englishMeaning: "Servant of Allah", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Abdulrahman", gender: "boy", urduMeaning: "رحمٰن کا بندہ", englishMeaning: "Servant of the Most Merciful", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Ahmed", gender: "boy", urduMeaning: "سب سے زیادہ قابلِ تعریف", englishMeaning: "Most commendable", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Saud", gender: "boy", urduMeaning: "خوش بخت، خوش قسمت", englishMeaning: "Fortunate, happy", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Fahad", gender: "boy", urduMeaning: "چیتا، تیندوا", englishMeaning: "Leopard", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Khalid", gender: "boy", urduMeaning: "ہمیشہ رہنے والا", englishMeaning: "Eternal, everlasting", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Faisal", gender: "boy", urduMeaning: "فیصلہ کرنے والا", englishMeaning: "Decisive, judge", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Sultan", gender: "boy", urduMeaning: "حاکم، اقتدار", englishMeaning: "Ruler, authority", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Turki", gender: "boy", urduMeaning: "ترک سے متعلق", englishMeaning: "Related to Turkic origin", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Nasser", gender: "boy", urduMeaning: "مدد کرنے والا، فاتح", englishMeaning: "Helper, victor", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Majed", gender: "boy", urduMeaning: "شاندار، معزز", englishMeaning: "Glorious, noble", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Rashid", gender: "boy", urduMeaning: "ہدایت یافتہ، سمجھدار", englishMeaning: "Rightly guided, wise", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Omar", gender: "boy", urduMeaning: "طویل عمر والا", englishMeaning: "Long-lived", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Saad", gender: "boy", urduMeaning: "خوش بختی، خوشی", englishMeaning: "Good fortune, happiness", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Bandar", gender: "boy", urduMeaning: "سمندر، بندرگاہ", englishMeaning: "Port, harbor", origin: "Arabic / Persian", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Walid", gender: "boy", urduMeaning: "نوزائیدہ بچہ", englishMeaning: "Newborn child", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Yousef", gender: "boy", urduMeaning: "اللہ اضافہ کرے", englishMeaning: "God increases", origin: "Arabic / Hebrew", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Mishal", gender: "boy", urduMeaning: "مشعل، روشنی کا ذریعہ", englishMeaning: "Torch, source of light", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Badr", gender: "boy", urduMeaning: "پورا چاند", englishMeaning: "Full moon", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },

{ name: "Noor", gender: "both", urduMeaning: "روشنی", englishMeaning: "Light", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Iman", gender: "both", urduMeaning: "ایمان، یقین", englishMeaning: "Faith, belief", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Amal", gender: "both", urduMeaning: "امید", englishMeaning: "Hope", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },
{ name: "Wissam", gender: "both", urduMeaning: "تمغہ، اعزاز", englishMeaning: "Medal, honor", origin: "Arabic", religion: "Other", country: "Saudi Arabia" },
{ name: "Anwar", gender: "both", urduMeaning: "زیادہ روشن", englishMeaning: "More radiant", origin: "Arabic", religion: "Islamic", country: "Saudi Arabia" },

// ==================== SYRIA ====================

{ name: "Fatima", gender: "girl", urduMeaning: "پاکیزہ، پرہیزگار", englishMeaning: "Pure, one who abstains", origin: "Arabic", religion: "Islamic", country: "Syria" },
{ name: "Mariam", gender: "girl", urduMeaning: "پاکیزہ، عبادت گزار", englishMeaning: "Pure, devoted", origin: "Arabic / Hebrew", religion: "Islamic", country: "Syria" },
{ name: "Aisha", gender: "girl", urduMeaning: "زندہ، خوشحال", englishMeaning: "Alive, living", origin: "Arabic", religion: "Islamic", country: "Syria" },
{ name: "Zainab", gender: "girl", urduMeaning: "خوشبودار پھول", englishMeaning: "Fragrant flower", origin: "Arabic", religion: "Islamic", country: "Syria" },
{ name: "Rania", gender: "girl", urduMeaning: "غور سے دیکھنے والی", englishMeaning: "Gazing, looking attentively", origin: "Arabic", religion: "Islamic", country: "Syria" },
{ name: "Laila", gender: "girl", urduMeaning: "رات", englishMeaning: "Night", origin: "Arabic", religion: "Islamic", country: "Syria" },
{ name: "Hala", gender: "girl", urduMeaning: "چاند کے گرد ہالہ", englishMeaning: "Halo around the moon", origin: "Arabic", religion: "Islamic", country: "Syria" },
{ name: "Rima", gender: "girl", urduMeaning: "سفید ہرن", englishMeaning: "White gazelle", origin: "Arabic", religion: "Islamic", country: "Syria" },
{ name: "Dima", gender: "girl", urduMeaning: "مسلسل ہلکی بارش", englishMeaning: "Gentle continuous rain", origin: "Arabic", religion: "Islamic", country: "Syria" },
{ name: "Razan", gender: "girl", urduMeaning: "وقار، سنجیدگی", englishMeaning: "Dignity, composure", origin: "Arabic", religion: "Islamic", country: "Syria" },
{ name: "Lina", gender: "girl", urduMeaning: "نرم، نازک", englishMeaning: "Tender, delicate", origin: "Arabic", religion: "Islamic", country: "Syria" },
{ name: "Hiba", gender: "girl", urduMeaning: "تحفہ، عطیہ", englishMeaning: "Gift", origin: "Arabic", religion: "Islamic", country: "Syria" },
{ name: "Samar", gender: "girl", urduMeaning: "رات کی گفتگو", englishMeaning: "Evening conversation", origin: "Arabic", religion: "Islamic", country: "Syria" },
{ name: "Nour", gender: "girl", urduMeaning: "روشنی", englishMeaning: "Light", origin: "Arabic", religion: "Islamic", country: "Syria" },
{ name: "Amal", gender: "girl", urduMeaning: "امید", englishMeaning: "Hope", origin: "Arabic", religion: "Islamic", country: "Syria" },
{ name: "Wafa", gender: "girl", urduMeaning: "وفاداری", englishMeaning: "Loyalty, faithfulness", origin: "Arabic", religion: "Islamic", country: "Syria" },
{ name: "Hanan", gender: "girl", urduMeaning: "شفقت، محبت", englishMeaning: "Compassion, tenderness", origin: "Arabic", religion: "Islamic", country: "Syria" },
{ name: "Sana", gender: "girl", urduMeaning: "چمک، شان", englishMeaning: "Radiance, brilliance", origin: "Arabic", religion: "Islamic", country: "Syria" },
{ name: "Basma", gender: "girl", urduMeaning: "مسکراہٹ", englishMeaning: "Smile", origin: "Arabic", religion: "Islamic", country: "Syria" },
{ name: "Abeer", gender: "girl", urduMeaning: "خوشبو، مہک", englishMeaning: "Fragrance", origin: "Arabic", religion: "Islamic", country: "Syria" },

{ name: "Mohamed", gender: "boy", urduMeaning: "سب سے زیادہ تعریف کیا گیا", englishMeaning: "Most praised", origin: "Arabic", religion: "Islamic", country: "Syria" },
{ name: "Ahmed", gender: "boy", urduMeaning: "سب سے زیادہ قابلِ تعریف", englishMeaning: "Most commendable", origin: "Arabic", religion: "Islamic", country: "Syria" },
{ name: "Mahmoud", gender: "boy", urduMeaning: "قابلِ تعریف", englishMeaning: "Praiseworthy", origin: "Arabic", religion: "Islamic", country: "Syria" },
{ name: "Omar", gender: "boy", urduMeaning: "طویل عمر والا", englishMeaning: "Long-lived", origin: "Arabic", religion: "Islamic", country: "Syria" },
{ name: "Ali", gender: "boy", urduMeaning: "بلند، اعلیٰ", englishMeaning: "High, exalted", origin: "Arabic", religion: "Islamic", country: "Syria" },
{ name: "Hassan", gender: "boy", urduMeaning: "خوبصورت، اچھا", englishMeaning: "Good, handsome", origin: "Arabic", religion: "Islamic", country: "Syria" },
{ name: "Hussein", gender: "boy", urduMeaning: "خوبصورت، حسین", englishMeaning: "Beautiful, good", origin: "Arabic", religion: "Islamic", country: "Syria" },
{ name: "Yousef", gender: "boy", urduMeaning: "اللہ اضافہ کرے", englishMeaning: "God increases", origin: "Arabic / Hebrew", religion: "Islamic", country: "Syria" },
{ name: "Ibrahim", gender: "boy", urduMeaning: "بہت سی قوموں کا باپ", englishMeaning: "Father of many nations", origin: "Arabic / Hebrew", religion: "Islamic", country: "Syria" },
{ name: "Khaled", gender: "boy", urduMeaning: "ہمیشہ رہنے والا", englishMeaning: "Eternal, everlasting", origin: "Arabic", religion: "Islamic", country: "Syria" },
{ name: "Tarek", gender: "boy", urduMeaning: "رات کو آنے والا، صبح کا ستارہ", englishMeaning: "Night visitor, morning star", origin: "Arabic", religion: "Islamic", country: "Syria" },
{ name: "Samir", gender: "boy", urduMeaning: "رات کی گفتگو کا ساتھی", englishMeaning: "Evening companion", origin: "Arabic", religion: "Islamic", country: "Syria" },
{ name: "Fadi", gender: "boy", urduMeaning: "نجات دینے والا", englishMeaning: "Redeemer, savior", origin: "Arabic", religion: "Christian", country: "Syria" },
{ name: "George", gender: "boy", urduMeaning: "کاشتکار، کسان", englishMeaning: "Farmer, earthworker", origin: "Greek", religion: "Christian", country: "Syria" },
{ name: "Elias", gender: "boy", urduMeaning: "میرا خدا اللہ ہے", englishMeaning: "My God is Yahweh", origin: "Hebrew / Arabic", religion: "Christian", country: "Syria" },
{ name: "Nabil", gender: "boy", urduMeaning: "شریف، معزز", englishMeaning: "Noble, honorable", origin: "Arabic", religion: "Islamic", country: "Syria" },
{ name: "Bilal", gender: "boy", urduMeaning: "تازگی، نمی", englishMeaning: "Freshness, moisture", origin: "Arabic", religion: "Islamic", country: "Syria" },
{ name: "Anas", gender: "boy", urduMeaning: "محبت، دوستانہ پن", englishMeaning: "Affection, friendliness", origin: "Arabic", religion: "Islamic", country: "Syria" },
{ name: "Iyad", gender: "boy", urduMeaning: "طاقت، مدد", englishMeaning: "Strength, support", origin: "Arabic", religion: "Islamic", country: "Syria" },
{ name: "Walid", gender: "boy", urduMeaning: "نوزائیدہ بچہ", englishMeaning: "Newborn child", origin: "Arabic", religion: "Islamic", country: "Syria" },

{ name: "Nour", gender: "both", urduMeaning: "روشنی", englishMeaning: "Light", origin: "Arabic", religion: "Islamic", country: "Syria" },
{ name: "Iman", gender: "both", urduMeaning: "ایمان، یقین", englishMeaning: "Faith, belief", origin: "Arabic", religion: "Islamic", country: "Syria" },
{ name: "Jihad", gender: "both", urduMeaning: "جدوجہد، کوشش", englishMeaning: "Struggle, effort", origin: "Arabic", religion: "Islamic", country: "Syria" },
{ name: "Amal", gender: "both", urduMeaning: "امید", englishMeaning: "Hope", origin: "Arabic", religion: "Islamic", country: "Syria" },
{ name: "Wissam", gender: "both", urduMeaning: "تمغہ، اعزاز", englishMeaning: "Medal, honor", origin: "Arabic", religion: "Other", country: "Syria" },

// ==================== TURKEY ====================

{ name: "Ayşe", gender: "girl", urduMeaning: "زندہ، خوشحال", englishMeaning: "Alive, living", origin: "Turkish / Arabic", religion: "Islamic", country: "Turkey" },
{ name: "Fatma", gender: "girl", urduMeaning: "پاکیزہ، پرہیزگار", englishMeaning: "Pure, one who abstains", origin: "Turkish / Arabic", religion: "Islamic", country: "Turkey" },
{ name: "Emine", gender: "girl", urduMeaning: "قابلِ اعتماد، امانت دار", englishMeaning: "Trustworthy, faithful", origin: "Turkish / Arabic", religion: "Islamic", country: "Turkey" },
{ name: "Hatice", gender: "girl", urduMeaning: "وقت سے پہلے پیدا ہونے والی", englishMeaning: "Early-born", origin: "Turkish / Arabic", religion: "Islamic", country: "Turkey" },
{ name: "Zeynep", gender: "girl", urduMeaning: "خوشبودار پھول", englishMeaning: "Fragrant flower", origin: "Turkish / Arabic", religion: "Islamic", country: "Turkey" },
{ name: "Elif", gender: "girl", urduMeaning: "الف، نازک اور خوبصورت", englishMeaning: "Slender, graceful", origin: "Turkish / Arabic", religion: "Islamic", country: "Turkey" },
{ name: "Meryem", gender: "girl", urduMeaning: "پاکیزہ، عبادت گزار", englishMeaning: "Pure, devoted", origin: "Turkish / Hebrew", religion: "Islamic", country: "Turkey" },
{ name: "Özlem", gender: "girl", urduMeaning: "آرزو، تڑپ", englishMeaning: "Longing, yearning", origin: "Turkish", religion: "Other", country: "Turkey" },
{ name: "Hülya", gender: "girl", urduMeaning: "خواب، خیال", englishMeaning: "Dream, reverie", origin: "Turkish / Arabic", religion: "Other", country: "Turkey" },
{ name: "Yasemin", gender: "girl", urduMeaning: "چنبیلی کا پھول", englishMeaning: "Jasmine flower", origin: "Turkish / Persian", religion: "Other", country: "Turkey" },
{ name: "Sevim", gender: "girl", urduMeaning: "محبوب، پیاری", englishMeaning: "Lovable, dear", origin: "Turkish", religion: "Other", country: "Turkey" },
{ name: "Şerife", gender: "girl", urduMeaning: "معزز، شریف", englishMeaning: "Honorable, noble", origin: "Turkish / Arabic", religion: "Islamic", country: "Turkey" },
{ name: "Dilek", gender: "girl", urduMeaning: "خواہش، آرزو", englishMeaning: "Wish, desire", origin: "Turkish", religion: "Other", country: "Turkey" },
{ name: "Aysel", gender: "girl", urduMeaning: "چاند جیسی، چاندنی", englishMeaning: "Moon-like, moonlight", origin: "Turkish", religion: "Other", country: "Turkey" },
{ name: "Fadime", gender: "girl", urduMeaning: "پاکیزہ، پرہیزگار", englishMeaning: "Pure, one who abstains", origin: "Turkish / Arabic", religion: "Islamic", country: "Turkey" },
{ name: "Leyla", gender: "girl", urduMeaning: "رات", englishMeaning: "Night", origin: "Turkish / Arabic", religion: "Islamic", country: "Turkey" },
{ name: "Zehra", gender: "girl", urduMeaning: "روشن، چمکدار", englishMeaning: "Bright, radiant", origin: "Turkish / Arabic", religion: "Islamic", country: "Turkey" },
{ name: "Esra", gender: "girl", urduMeaning: "رات کا سفر", englishMeaning: "Night journey", origin: "Turkish / Arabic", religion: "Islamic", country: "Turkey" },
{ name: "Merve", gender: "girl", urduMeaning: "مروہ، مقدس پہاڑی", englishMeaning: "Marwah, sacred hill", origin: "Turkish / Arabic", religion: "Islamic", country: "Turkey" },
{ name: "Melek", gender: "girl", urduMeaning: "فرشتہ", englishMeaning: "Angel", origin: "Turkish / Arabic", religion: "Islamic", country: "Turkey" },

{ name: "Mehmet", gender: "boy", urduMeaning: "سب سے زیادہ تعریف کیا گیا", englishMeaning: "Most praised", origin: "Turkish / Arabic", religion: "Islamic", country: "Turkey" },
{ name: "Mustafa", gender: "boy", urduMeaning: "منتخب کیا ہوا", englishMeaning: "The chosen one", origin: "Turkish / Arabic", religion: "Islamic", country: "Turkey" },
{ name: "Ahmet", gender: "boy", urduMeaning: "سب سے زیادہ قابلِ تعریف", englishMeaning: "Most commendable", origin: "Turkish / Arabic", religion: "Islamic", country: "Turkey" },
{ name: "Ali", gender: "boy", urduMeaning: "بلند، اعلیٰ", englishMeaning: "High, exalted", origin: "Turkish / Arabic", religion: "Islamic", country: "Turkey" },
{ name: "Hasan", gender: "boy", urduMeaning: "خوبصورت، اچھا", englishMeaning: "Good, handsome", origin: "Turkish / Arabic", religion: "Islamic", country: "Turkey" },
{ name: "Hüseyin", gender: "boy", urduMeaning: "خوبصورت، حسین", englishMeaning: "Beautiful, good", origin: "Turkish / Arabic", religion: "Islamic", country: "Turkey" },
{ name: "İbrahim", gender: "boy", urduMeaning: "بہت سی قوموں کا باپ", englishMeaning: "Father of many nations", origin: "Turkish / Arabic", religion: "Islamic", country: "Turkey" },
{ name: "Murat", gender: "boy", urduMeaning: "خواہش، مقصد", englishMeaning: "Wish, purpose", origin: "Turkish / Arabic", religion: "Islamic", country: "Turkey" },
{ name: "İsmail", gender: "boy", urduMeaning: "اللہ سنتا ہے", englishMeaning: "God hears", origin: "Turkish / Arabic", religion: "Islamic", country: "Turkey" },
{ name: "Ömer", gender: "boy", urduMeaning: "طویل عمر والا", englishMeaning: "Long-lived", origin: "Turkish / Arabic", religion: "Islamic", country: "Turkey" },
{ name: "Osman", gender: "boy", urduMeaning: "حکیم، دانا", englishMeaning: "Wise, knowledgeable", origin: "Turkish / Arabic", religion: "Islamic", country: "Turkey" },
{ name: "Halil", gender: "boy", urduMeaning: "قریبی دوست", englishMeaning: "Close friend", origin: "Turkish / Arabic", religion: "Islamic", country: "Turkey" },
{ name: "Yusuf", gender: "boy", urduMeaning: "اللہ اضافہ کرے", englishMeaning: "God increases", origin: "Turkish / Arabic", religion: "Islamic", country: "Turkey" },
{ name: "Abdullah", gender: "boy", urduMeaning: "اللہ کا بندہ", englishMeaning: "Servant of Allah", origin: "Turkish / Arabic", religion: "Islamic", country: "Turkey" },
{ name: "Süleyman", gender: "boy", urduMeaning: "پُرامن", englishMeaning: "Peaceful", origin: "Turkish / Arabic", religion: "Islamic", country: "Turkey" },
{ name: "Fatih", gender: "boy", urduMeaning: "فاتح، کامیاب", englishMeaning: "Conqueror, victor", origin: "Turkish / Arabic", religion: "Islamic", country: "Turkey" },
{ name: "Mahmut", gender: "boy", urduMeaning: "قابلِ تعریف", englishMeaning: "Praiseworthy", origin: "Turkish / Arabic", religion: "Islamic", country: "Turkey" },
{ name: "Hakan", gender: "boy", urduMeaning: "حاکم، بادشاہ", englishMeaning: "Ruler, sovereign", origin: "Turkish", religion: "Other", country: "Turkey" },
{ name: "Adem", gender: "boy", urduMeaning: "انسان، آدم", englishMeaning: "Man, Adam", origin: "Turkish / Hebrew", religion: "Islamic", country: "Turkey" },
{ name: "Kadir", gender: "boy", urduMeaning: "قادر، طاقتور", englishMeaning: "Powerful, capable", origin: "Turkish / Arabic", religion: "Islamic", country: "Turkey" },

{ name: "Sultan", gender: "both", urduMeaning: "حاکم، اقتدار", englishMeaning: "Ruler, authority", origin: "Turkish / Arabic", religion: "Islamic", country: "Turkey" },
{ name: "Derya", gender: "both", urduMeaning: "سمندر", englishMeaning: "Sea, ocean", origin: "Turkish / Persian", religion: "Other", country: "Turkey" },
{ name: "Ümit", gender: "both", urduMeaning: "امید", englishMeaning: "Hope", origin: "Turkish", religion: "Other", country: "Turkey" },
{ name: "Deniz", gender: "both", urduMeaning: "سمندر", englishMeaning: "Sea", origin: "Turkish", religion: "Other", country: "Turkey" },
{ name: "Özgür", gender: "both", urduMeaning: "آزاد", englishMeaning: "Free", origin: "Turkish", religion: "Other", country: "Turkey" },

// ==================== YEMEN ====================

{ name: "Fatima", gender: "girl", urduMeaning: "پاکیزہ، پرہیزگار", englishMeaning: "Pure, one who abstains", origin: "Arabic", religion: "Islamic", country: "Yemen" },
{ name: "Mona", gender: "girl", urduMeaning: "خواہشات، تمنائیں", englishMeaning: "Wishes, desires", origin: "Arabic", religion: "Islamic", country: "Yemen" },
{ name: "Amal", gender: "girl", urduMeaning: "امید", englishMeaning: "Hope", origin: "Arabic", religion: "Islamic", country: "Yemen" },
{ name: "Jamila", gender: "girl", urduMeaning: "خوبصورت", englishMeaning: "Beautiful", origin: "Arabic", religion: "Islamic", country: "Yemen" },
{ name: "Mariam", gender: "girl", urduMeaning: "پاکیزہ، عبادت گزار", englishMeaning: "Pure, devoted", origin: "Arabic / Hebrew", religion: "Islamic", country: "Yemen" },
{ name: "Hoda", gender: "girl", urduMeaning: "ہدایت، رہنمائی", englishMeaning: "Guidance", origin: "Arabic", religion: "Islamic", country: "Yemen" },
{ name: "Hana", gender: "girl", urduMeaning: "خوشی، مسرت", englishMeaning: "Happiness, bliss", origin: "Arabic", religion: "Islamic", country: "Yemen" },
{ name: "Nour", gender: "girl", urduMeaning: "روشنی", englishMeaning: "Light", origin: "Arabic", religion: "Islamic", country: "Yemen" },
{ name: "Afrah", gender: "girl", urduMeaning: "خوشیاں، مسرتیں", englishMeaning: "Joys, celebrations", origin: "Arabic", religion: "Islamic", country: "Yemen" },
{ name: "Wafa", gender: "girl", urduMeaning: "وفاداری", englishMeaning: "Loyalty, faithfulness", origin: "Arabic", religion: "Islamic", country: "Yemen" },
{ name: "Hanan", gender: "girl", urduMeaning: "شفقت، محبت", englishMeaning: "Compassion, tenderness", origin: "Arabic", religion: "Islamic", country: "Yemen" },
{ name: "Samira", gender: "girl", urduMeaning: "رات کی ساتھی", englishMeaning: "Evening companion", origin: "Arabic", religion: "Islamic", country: "Yemen" },
{ name: "Ahlam", gender: "girl", urduMeaning: "خواب، امیدیں", englishMeaning: "Dreams, aspirations", origin: "Arabic", religion: "Islamic", country: "Yemen" },
{ name: "Ibtisam", gender: "girl", urduMeaning: "مسکراہٹ", englishMeaning: "Smile", origin: "Arabic", religion: "Islamic", country: "Yemen" },
{ name: "Abeer", gender: "girl", urduMeaning: "خوشبو، مہک", englishMeaning: "Fragrance", origin: "Arabic", religion: "Islamic", country: "Yemen" },
{ name: "Elham", gender: "girl", urduMeaning: "الہام", englishMeaning: "Inspiration", origin: "Arabic", religion: "Islamic", country: "Yemen" },
{ name: "Asmaa", gender: "girl", urduMeaning: "بلند، اعلیٰ", englishMeaning: "Exalted, lofty", origin: "Arabic", religion: "Islamic", country: "Yemen" },
{ name: "Nadia", gender: "girl", urduMeaning: "امید سے بھرپور", englishMeaning: "Hopeful", origin: "Arabic / Slavic", religion: "Other", country: "Yemen" },
{ name: "Nawal", gender: "girl", urduMeaning: "تحفہ، عطیہ", englishMeaning: "Gift, blessing", origin: "Arabic", religion: "Islamic", country: "Yemen" },
{ name: "Manal", gender: "girl", urduMeaning: "کامیابی، حصول", englishMeaning: "Achievement, attainment", origin: "Arabic", religion: "Islamic", country: "Yemen" },

{ name: "Mohamed", gender: "boy", urduMeaning: "سب سے زیادہ تعریف کیا گیا", englishMeaning: "Most praised", origin: "Arabic", religion: "Islamic", country: "Yemen" },
{ name: "Saleh", gender: "boy", urduMeaning: "نیک، صالح", englishMeaning: "Righteous, virtuous", origin: "Arabic", religion: "Islamic", country: "Yemen" },
{ name: "Abdo", gender: "boy", urduMeaning: "بندہ، عبادت گزار", englishMeaning: "Servant, worshipper", origin: "Arabic", religion: "Islamic", country: "Yemen" },
{ name: "Ali", gender: "boy", urduMeaning: "بلند، اعلیٰ", englishMeaning: "High, exalted", origin: "Arabic", religion: "Islamic", country: "Yemen" },
{ name: "Ahmed", gender: "boy", urduMeaning: "سب سے زیادہ قابلِ تعریف", englishMeaning: "Most commendable", origin: "Arabic", religion: "Islamic", country: "Yemen" },
{ name: "Abdullah", gender: "boy", urduMeaning: "اللہ کا بندہ", englishMeaning: "Servant of Allah", origin: "Arabic", religion: "Islamic", country: "Yemen" },
{ name: "Nabil", gender: "boy", urduMeaning: "شریف، معزز", englishMeaning: "Noble, honorable", origin: "Arabic", religion: "Islamic", country: "Yemen" },
{ name: "Hassan", gender: "boy", urduMeaning: "خوبصورت، اچھا", englishMeaning: "Good, handsome", origin: "Arabic", religion: "Islamic", country: "Yemen" },
{ name: "Nasr", gender: "boy", urduMeaning: "فتح، کامیابی", englishMeaning: "Victory, triumph", origin: "Arabic", religion: "Islamic", country: "Yemen" },
{ name: "Khaled", gender: "boy", urduMeaning: "ہمیشہ رہنے والا", englishMeaning: "Eternal, everlasting", origin: "Arabic", religion: "Islamic", country: "Yemen" },
{ name: "Fayez", gender: "boy", urduMeaning: "کامیاب، فاتح", englishMeaning: "Successful, victorious", origin: "Arabic", religion: "Islamic", country: "Yemen" },
{ name: "Anwar", gender: "boy", urduMeaning: "زیادہ روشن", englishMeaning: "More radiant", origin: "Arabic", religion: "Islamic", country: "Yemen" },
{ name: "Naji", gender: "boy", urduMeaning: "نجات پانے والا", englishMeaning: "Safe, survivor", origin: "Arabic", religion: "Islamic", country: "Yemen" },
{ name: "Bandar", gender: "boy", urduMeaning: "بندرگاہ", englishMeaning: "Port, harbor", origin: "Arabic / Persian", religion: "Islamic", country: "Yemen" },
{ name: "Yahya", gender: "boy", urduMeaning: "زندہ، زندہ رہنے والا", englishMeaning: "Alive, living", origin: "Arabic / Hebrew", religion: "Islamic", country: "Yemen" },
{ name: "Ibrahim", gender: "boy", urduMeaning: "بہت سی قوموں کا باپ", englishMeaning: "Father of many nations", origin: "Arabic / Hebrew", religion: "Islamic", country: "Yemen" },
{ name: "Hussein", gender: "boy", urduMeaning: "خوبصورت، حسین", englishMeaning: "Beautiful, good", origin: "Arabic", religion: "Islamic", country: "Yemen" },
{ name: "Mahdi", gender: "boy", urduMeaning: "ہدایت یافتہ", englishMeaning: "Rightly guided", origin: "Arabic", religion: "Islamic", country: "Yemen" },
{ name: "Nayef", gender: "boy", urduMeaning: "بلند، اونچا", englishMeaning: "High, elevated", origin: "Arabic", religion: "Islamic", country: "Yemen" },
{ name: "Fahd", gender: "boy", urduMeaning: "چیتا، تیندوا", englishMeaning: "Leopard", origin: "Arabic", religion: "Islamic", country: "Yemen" },

{ name: "Nour", gender: "both", urduMeaning: "روشنی", englishMeaning: "Light", origin: "Arabic", religion: "Islamic", country: "Yemen" },
{ name: "Iman", gender: "both", urduMeaning: "ایمان، یقین", englishMeaning: "Faith, belief", origin: "Arabic", religion: "Islamic", country: "Yemen" },
{ name: "Anwar", gender: "both", urduMeaning: "زیادہ روشن", englishMeaning: "More radiant", origin: "Arabic", religion: "Islamic", country: "Yemen" },
{ name: "Amal", gender: "both", urduMeaning: "امید", englishMeaning: "Hope", origin: "Arabic", religion: "Islamic", country: "Yemen" },
{ name: "Wafa", gender: "both", urduMeaning: "وفاداری", englishMeaning: "Loyalty, faithfulness", origin: "Arabic", religion: "Islamic", country: "Yemen" },


];