const ar = {
  language: "اللغة", nav: { home: "الرئيسية", about: "من نحن", regions: "المناطق", categories: "الفئات", popular: "أسماء شائعة", search: "ابحث عن أي شيء...", menu: "القائمة", main: "التنقل الرئيسي", clear: "مسح البحث", searching: "جارٍ البحث...", noResults: "لا توجد نتائج لـ «{query}»", type: { Name: "اسم", Region: "منطقة", Category: "فئة", Page: "صفحة" } },
  search: { placeholder: "ابحث عن اسم أو معنى أو بلد أو أصل...", label: "ابحث عن الأسماء والمعاني والبلدان والأصول", button: "بحث", notFound: "لم يتم العثور على أسماء", description: "لم نعثر على هذا الاسم. جرّب تهجئة أخرى أو استكشف المجموعة كاملة.", explore: "استكشف الأسماء", goHome: "الرئيسية", start: "ابدأ الكتابة للبحث في مجموعة الأسماء.", tryCountry: "جرّب «France»", tryOrigin: "جرّب «Arabic»", tryCategory: "جرّب «Popular Names»" },
  home: { title: "وراء كل اسم حكاية.", description: "ابحث بين آلاف الأسماء حسب البلد والمنطقة والجنس والدين والأصل والمعنى، واعثر على الاسم المناسب لك.", featured: "أسماء مختارة", exploreRegion: "استكشف حسب المنطقة", discoverWorld: "اكتشف أسماء من حول العالم", regionDescription: "اكتشف أسماء جميلة ومعانيها وأصولها من مختلف البلدان والمناطق.", meaningTitle: "يحمل الاسم معنى قبل أن يحمله صاحبه.", meaningDescription: "ابدأ بالشعور لا بالتهجئة، وتصفّح الأسماء بحسب معانيها.", howTitle: "ثلاث طرق للبحث، واسم مناسب واحد.", searchHow: "ابحث بطريقتك", searchHowText: "اكتب اسمًا أو صوتًا أو بلدًا أو معنى؛ البحث يفهمها جميعًا.", narrow: "ضيّق خياراتك", narrowText: "صفِّ النتائج حسب الأصل أو الدين أو المنطقة أو الجنس.", save: "احتفظ بما تحب", saveText: "أنشئ قائمة مختصرة أثناء التصفح كي لا يفوتك اسم جميل.", shortlist: "احتفظ بقائمة مختصرة أثناء التصفح.", startSearch: "ابدأ البحث", trySearch: "جرّب {query}", exploreMore: "استكشف {region}", countriesCount: "{count} بلدان", more: "+{count} أخرى" },
  region: { europe: "أوروبا", middleEast: "الشرق الأوسط", southAsia: "جنوب آسيا", eastAsia: "شرق آسيا", southeastAsia: "جنوب شرق آسيا", centralAsia: "وسط آسيا", africa: "أفريقيا", northAmerica: "أمريكا الشمالية", latinAmerica: "أمريكا اللاتينية / الجنوبية", caribbean: "الكاريبي", oceania: "أوقيانوسيا / أستراليا", explore: "استكشف {region}", countries: "البلدان", regionLabel: "المنطقة", names: "الأسماء", chooseCountry: "اختر بلدًا", selectCountry: "اختر بلدًا لاستكشاف أسمائه وتقاليد التسمية فيه.", backHome: "العودة للرئيسية", exploreNames: "استكشف الأسماء" },
  country: { backTo: "العودة إلى {region}", hero: "استكشف الأسماء وتقاليد التسمية في {country}.", namesFrom: "أسماء من {country}", discover: "اكتشف أسماء تحكي قصة.", description: "استكشف أسماء {country} الجميلة ومعانيها وأصولها.", search: "ابحث عن أسماء في {country}...", filterGender: "تصفية الأسماء حسب الجنس", girls: "بنات", boys: "أولاد", both: "مشتركة", religion: "الدين", origin: "الأصل", popularity: "الانتشار", state: "الولاية", city: "المدينة", all: "الكل", nameCount: "{count} اسم", noNames: "لم يتم العثور على أسماء", noNamesHelp: "جرّب بحثًا آخر أو اختر فئة مختلفة.", moreNames: "استكشف مزيدًا من الأسماء وتقاليد التسمية في {country}", traditionalBelief: "معتقد تقليدي" },
  name: { back: "العودة إلى البحث", discovery: "اكتشاف الاسم", genderName: "اسم {gender} · {region}", meaning: "المعنى", story: "اكتشف حكاية هذا الاسم الجميل وأصله وسماته." }, gender: { girl: "أنثى", boy: "ذكر", both: "مشترك", girlName: "اسم أنثوي", boyName: "اسم ذكوري", unisexName: "اسم مشترك" },
  detail: { country: "البلد", religion: "الدين", popularity: "الانتشار", luckyNumber: "رقم الحظ", meaning: "المعنى", copy: "نسخ", copied: "تم النسخ ✓", share: "مشاركة", linkCopied: "تم نسخ الرابط", copyDetails: "تم نسخ تفاصيل الاسم", shareDetails: "تم نسخ تفاصيل المشاركة", shareName: "مشاركة {name}", copyName: "نسخ تفاصيل {name}" },
  about: { eyebrow: "عن NameWorlds", title: "لكل اسم حكاية", intro: "يساعدك NameWorlds على اكتشاف أسماء ذات معنى وتراث وشخصية. استكشف أسماء من حول العالم وأصولها ومعانيها الأردية وصلاتها الدينية وأرقام الحظ والحكايات التي تجعلها مميزة.", explore: "استكشف الأسماء", starting: "بداية مدروسة", offer: "ما نقدمه", offerIntro: "كل ما تحتاجه للانتقال من فكرة ملهمة إلى اسم تشعر أنه مناسب تمامًا.", meanings: "معاني الأسماء", meaningsText: "افهم الإحساس والتاريخ والحكاية التي يحملها كل اسم.", urduMeanings: "المعاني الأردية", urduMeaningsText: "استكشف أسماء بمعانٍ أردية واضحة تسهّل الاختيار.", origins: "الأصول والثقافات", originsText: "اكتشف أصول الأسماء والتقاليد التي صاغتها.", religion: "الدين", religionText: "اعثر على أسماء مرتبطة بالمعتقدات والتقاليد المهمة لك.", lucky: "أرقام الحظ", luckyText: "تعرّف على جانب إضافي من رمزية كل اسم وشخصيته.", rarePopular: "أسماء نادرة وشائعة", rarePopularText: "قارن بين الأسماء المحبوبة دائمًا والأسماء المميزة.", purpose: "هدفنا", purposeTitle: "نساعدك في العثور على اسم ذي معنى.", purposeText: "قد يكون اختيار الاسم أمرًا شخصيًا ومبهجًا ومربكًا أحيانًا. نسهّل هذه الرحلة بجمع معلومات مفيدة في مكان هادئ ومرحّب، لتقودك كل عملية بحث إلى اسم يحمل حكاية تستحق أن تستمر.", begin: "ابدأ الاستكشاف" },
  notFound: { eyebrow: "استراحة قصيرة", title: "عذرًا! يبدو أن هذا الاسم تاه.", description: "تعذّر العثور على الصفحة المطلوبة. دعنا نساعدك على اكتشاف شيء جميل بدلًا منها.", explore: "استكشف الأسماء", home: "الرئيسية", keep: "تابع الاستكشاف", looking: "هل تبحث عن الاسم المثالي؟", suggestions: "استكشف الأسماء حسب البلد أو المعنى أو الأصل أو الفئة.", discover: "اكتشف الأسماء", quick: "روابط سريعة للأسماء", girls: "أسماء البنات", boys: "أسماء الأولاد", unisex: "أسماء مشتركة" },
  footer: { tagline: "أسماء جميلة وذات معنى من كل أنحاء العالم.", email: "البريد الإلكتروني", join: "انضم", joined: "أُضيف بريدك إلى القائمة", explore: "استكشف", allNames: "كل الأسماء", girls: "أسماء البنات", boys: "أسماء الأولاد", unisex: "أسماء مشتركة", guides: "أدلة", meanings: "معاني الأسماء", origins: "أصول الأسماء", lucky: "أرقام الحظ", islamic: "أسماء إسلامية", finder: "ابحث عن اسم", countries: "البلدان", info: "معلومات", about: "من نحن", contact: "اتصل بنا", privacy: "سياسة الخصوصية", terms: "الشروط", disclaimer: "إخلاء المسؤولية", backTop: "العودة إلى الأعلى", newsletter: "الاشتراك في النشرة البريدية" },
  common: { name: "اسم", names: "الأسماء", explore: "استكشف", all: "الكل", loading: "جارٍ التحميل...", error: "حدث خطأ. يُرجى المحاولة مرة أخرى." }, religion: { Islamic: "إسلامي", Christian: "مسيحي", Jewish: "يهودي", Hindu: "هندوسي", Sikh: "سيخي", Buddhist: "بوذي", Other: "أخرى", None: "لا شيء" }, popularity: { Rare: "نادر", Uncommon: "غير شائع", Popular: "شائع", "Very Popular": "شائع جدًا" }
} as const;
export default ar;
