const de = {

  language:"Sprache",nav:{home:"Startseite",about:"Über uns",regions:"Regionen",categories:"Kategorien",popular:"Beliebte Namen",search:"Alles durchsuchen...",menu:"Menü",main:"Hauptnavigation",clear:"Suche löschen",searching:"Suche läuft...",noResults:"Keine Ergebnisse für „{query}“",type:{Name:"Name",Region:"Region",Category:"Kategorie",Page:"Seite"}},

  search:{placeholder:"Name, Bedeutung, Land oder Herkunft suchen...",label:"Namen, Bedeutungen, Länder oder Herkunft suchen",button:"Suchen",notFound:"Keine Namen gefunden",description:"Diesen Namen konnten wir nicht finden. Versuche eine andere Schreibweise oder stöbere in der Sammlung.",explore:"Namen entdecken",goHome:"Zur Startseite",start:"Gib etwas ein, um Namen zu suchen.",tryCountry:"Probiere „France“",tryOrigin:"Probiere „Arabic“",tryCategory:"Probiere „Popular Names“"},

  home:{title:"Jeder Name erzählt eine Geschichte.",description:"Entdecke Tausende Namen nach Land, Region, Geschlecht, Religion, Herkunft und Bedeutung und finde den passenden Namen.",featured:"Ausgewählte Namen",exploreRegion:"Nach Region entdecken",discoverWorld:"Namen aus aller Welt entdecken",regionDescription:"Entdecke schöne Namen, Bedeutungen und Ursprünge aus verschiedenen Ländern und Regionen.",meaningTitle:"Namen tragen Bedeutung, lange bevor sie eine Person begleiten.",meaningDescription:"Beginne mit einem Gefühl statt mit der Schreibweise und entdecke Namen nach ihrer Bedeutung.",howTitle:"Drei Wege zum passenden Namen.",searchHow:"Suche auf deine Weise",searchHowText:"Gib einen Namen, Klang, ein Land oder eine Bedeutung ein – die Suche versteht alles.",narrow:"Auswahl eingrenzen",narrowText:"Filtere nach Herkunft, Religion, Region oder Geschlecht.",save:"Favoriten merken",saveText:"Speichere Namen beim Stöbern, damit dir kein guter Name entgeht.",shortlist:"Merke dir Favoriten beim Stöbern.",startSearch:"Suche starten",trySearch:"Probiere {query}",exploreMore:"{region} entdecken",countriesCount:"{count} Länder",more:"+{count} weitere"},

  region:{europe:"Europa",middleEast:"Naher Osten",southAsia:"Südasien",eastAsia:"Ostasien",southeastAsia:"Südostasien",centralAsia:"Zentralasien",africa:"Afrika",northAmerica:"Nordamerika",latinAmerica:"Lateinamerika / Südamerika",caribbean:"Karibik",oceania:"Ozeanien / Australien",explore:"{region} entdecken",countries:"Länder",regionLabel:"Region",names:"Namen",chooseCountry:"Land auswählen",selectCountry:"Wähle ein Land, um Namen und Namenstraditionen zu entdecken.",backHome:"Zur Startseite",exploreNames:"Namen entdecken"},

  country:{backTo:"Zurück zu {region}",hero:"Entdecke Namen und Namenstraditionen aus {country}.",namesFrom:"Namen aus {country}",discover:"Entdecke Namen mit einer Geschichte.",description:"Entdecke schöne Namen aus {country}, ihre Bedeutungen und Ursprünge.",search:"Namen aus {country} suchen...",filterGender:"Namen nach Geschlecht filtern",girls:"Mädchen",boys:"Jungen",both:"Unisex",religion:"Religion",origin:"Herkunft",popularity:"Beliebtheit",state:"Bundesstaat",city:"Stadt",all:"Alle",nameCount:"{count} Namen",noNames:"Keine Namen gefunden",noNamesHelp:"Versuche eine andere Suche oder wähle eine andere Kategorie.",moreNames:"Entdecke weitere Namen und Traditionen aus {country}",traditionalBelief:"Traditioneller Glaube"},

  name:{back:"Zurück zur Suche",discovery:"Namensentdeckung",genderName:"{gender}name · {region}",meaning:"Bedeutung",story:"Entdecke die Geschichte, Herkunft und den Charakter dieses Namens."},

  gender:{girl:"Mädchen",boy:"Junge",both:"Unisex",girlName:"Mädchenname",boyName:"Jungenname",unisexName:"Unisexname"},

  detail:{country:"Land",religion:"Religion",popularity:"Beliebtheit",luckyNumber:"Glückszahl",meaning:"Bedeutung",copy:"Kopieren",copied:"Kopiert ✓",share:"Teilen",linkCopied:"Link kopiert",copyDetails:"Namensdetails kopiert",shareDetails:"Teildetails kopiert",shareName:"{name} teilen",copyName:"Details zu {name} kopieren"},

  about:{eyebrow:"Über NameWorlds",title:"Jeder Name hat eine Geschichte",intro:"NameWorlds hilft dir, Namen mit Bedeutung, Herkunft und Charakter zu entdecken. Erkunde Namen aus aller Welt, ihre Ursprünge, Urdu-Bedeutungen, religiösen Bezüge, Glückszahlen und Geschichten.",explore:"Namen entdecken",starting:"Ein durchdachter Anfang",offer:"Unser Angebot",offerIntro:"Alles, was du brauchst, um aus einer ersten Idee einen Namen zu finden, der sich richtig anfühlt.",meanings:"Namensbedeutungen",meaningsText:"Verstehe das Gefühl, die Geschichte und die Erzählung hinter jedem Namen.",urduMeanings:"Urdu-Bedeutungen",urduMeaningsText:"Entdecke Namen mit klaren Urdu-Bedeutungen.",origins:"Herkunft und Kulturen",originsText:"Erfahre, woher Namen stammen und welche Traditionen sie geprägt haben.",religion:"Religion",religionText:"Finde Namen, die mit wichtigen Glaubensrichtungen und Traditionen verbunden sind.",lucky:"Glückszahlen",luckyText:"Entdecke eine weitere symbolische und persönliche Seite jedes Namens.",rarePopular:"Seltene und beliebte Namen",rarePopularText:"Vergleiche zeitlose Favoriten mit besonderen Namen, die noch darauf warten, entdeckt zu werden.",purpose:"Unser Ziel",purposeTitle:"Wir helfen dir, einen bedeutungsvollen Namen zu finden.",purposeText:"Einen Namen auszuwählen ist persönlich, schön und manchmal überwältigend. Wir möchten den Weg erleichtern und hilfreiche Informationen an einem ruhigen, einladenden Ort bündeln – damit jede Suche zu einer Geschichte führen kann, die es wert ist, weitergetragen zu werden.",begin:"Entdecken beginnen"},

  notFound:{eyebrow:"Ein kleiner Umweg",title:"Hoppla! Dieser Name scheint verschwunden zu sein.",description:"Die gesuchte Seite wurde nicht gefunden. Entdecke stattdessen etwas Schönes.",explore:"Namen entdecken",home:"Zur Startseite",keep:"Weiter entdecken",looking:"Suchst du den perfekten Namen?",suggestions:"Entdecke Namen nach Land, Bedeutung, Herkunft oder Kategorie.",discover:"Namen entdecken",quick:"Schnellzugriff auf Namen",girls:"Mädchennamen",boys:"Jungennamen",unisex:"Unisexnamen"},

  footer:{tagline:"Liebevolle, bedeutungsvolle Namen aus aller Welt.",email:"E-Mail-Adresse",join:"Abonnieren",joined:"Du stehst auf der Liste",explore:"Entdecken",allNames:"Alle Namen",girls:"Mädchennamen",boys:"Jungennamen",unisex:"Unisexnamen",guides:"Ratgeber",meanings:"Namensbedeutungen",origins:"Namensherkunft",lucky:"Glückszahlen",islamic:"Islamische Namen",finder:"Namenssuche",countries:"Länder",info:"Informationen",about:"Über uns",contact:"Kontakt",privacy:"Datenschutz",terms:"Nutzungsbedingungen",disclaimer:"Haftungsausschluss",backTop:"Nach oben",newsletter:"Newsletter-Anmeldung"},

  common:{name:"Name",names:"Namen",explore:"Entdecken",all:"Alle",loading:"Wird geladen...",error:"Etwas ist schiefgelaufen. Bitte versuche es erneut."},

  religion:{Islamic:"Islamisch",Christian:"Christlich",Jewish:"Jüdisch",Hindu:"Hinduistisch",Sikh:"Sikh",Buddhist:"Buddhistisch",Other:"Andere",None:"Keine"},

  popularity:{Rare:"Selten",Uncommon:"Ungewöhnlich",Popular:"Beliebt","Very Popular":"Sehr beliebt"}

} as const;

export default de;