const en = {
  language: "Language",
  languages: { en: "English", ur: "اردو", ar: "العربية", zh: "中文", es: "Español", fr: "Français", de: "Deutsch", ru: "Русский", hi: "हिन्दी", tr: "Türkçe" },
  nav: { home: "Home", about: "About Us", regions: "Regions", categories: "Categories", popular: "Popular Names", search: "Search anything...", menu: "Menu", main: "Main navigation", clear: "Clear search", searching: "Searching...", noResults: "No results found for “{query}”", type: { Name: "Name", Region: "Region", Category: "Category", Page: "Page" } },
  search: { placeholder: "Search a name, meaning, country or origin...", label: "Search names, meanings, countries or origins", button: "Search", notFound: "No names found", description: "We couldn’t find that name. Try another spelling or explore the full collection.", explore: "Explore Names", goHome: "Go Home", start: "Start typing to search the Names collection.", tryCountry: "Try “France”", tryOrigin: "Try “Arabic”", tryCategory: "Try “Popular Names”" },
  home: { title: "Every name carries a story.", description: "Search thousands of names by country, region, gender, religion, origin and meaning — and find the one that fits yours.", featured: "Featured names", exploreRegion: "Explore by Region", discoverWorld: "Discover Names Around the World", regionDescription: "Explore beautiful names, meanings and origins from different countries and regions.", meaningTitle: "Names carry meaning long before they carry a person.", meaningDescription: "Start from a feeling instead of a spelling — browse names grouped by what they mean.", howTitle: "Three ways in, one good name out.", searchHow: "Search however you think", searchHowText: "Type a name, a sound, a country or a meaning — the search understands all of them.", narrow: "Narrow it down", narrowText: "Filter by origin, religion, region or gender until the list feels like it’s actually yours.", save: "Save the ones you love", saveText: "Keep a running shortlist as you browse, so nothing good gets lost in the search.", shortlist: "Keep a shortlist as you browse.", startSearch: "Start searching", trySearch: "Try {query}", exploreMore: "Explore {region}", countriesCount: "{count} countries", more: "+{count} more" },
  region: { europe: "Europe", middleEast: "Middle East", southAsia: "South Asia", eastAsia: "East Asia", southeastAsia: "Southeast Asia", centralAsia: "Central Asia", africa: "Africa", northAmerica: "North America", latinAmerica: "Latin America / South America", caribbean: "Caribbean", oceania: "Oceania / Australia", explore: "Explore {region}", countries: "Countries", regionLabel: "Region", names: "Names", chooseCountry: "Choose a country", selectCountry: "Select a country to explore its names and naming traditions.", backHome: "Back to Home", exploreNames: "Explore Names" },
  country: { backTo: "Back to {region}", hero: "Explore names and naming traditions from {country}.", namesFrom: "Names from {country}", discover: "Discover names that tell a story.", description: "Explore beautiful names, their meanings and origins from {country}.", search: "Search names in {country}...", filterGender: "Filter names by gender", girls: "Girls", boys: "Boys", both: "Both", religion: "Religion", origin: "Origin", popularity: "Popularity", state: "State", city: "City", all: "All", nameCount: "{count} names", noNames: "No names found", noNamesHelp: "Try another search or choose a different category.", moreNames: "Explore more names and naming traditions from {country}", traditionalBelief: "Traditional belief" },
  name: { back: "Back to search", discovery: "Name discovery", genderName: "{gender} name · {region}", meaning: "Meaning", story: "Explore the story, origin, and character behind this beautiful name." },
  gender: { girl: "Girl", boy: "Boy", both: "Unisex", girlName: "Girl name", boyName: "Boy name", unisexName: "Unisex name" },
  detail: { country: "Country", religion: "Religion", popularity: "Popularity", luckyNumber: "Lucky Number", meaning: "Meaning", copy: "Copy", copied: "Copied ✓", share: "Share", linkCopied: "Link copied", copyDetails: "Name details copied", shareDetails: "Share details copied", shareName: "Share {name}", copyName: "Copy details for {name}" },
  about: { eyebrow: "About NameWorlds", title: "Every Name Has a Story", intro: "NameWorlds helps you discover names with meaning, heritage and character. Explore names from around the world, their origins, Urdu meanings, religious connections, lucky numbers and the stories that make them memorable.", explore: "Explore Names", starting: "A thoughtful starting point", offer: "What We Offer", offerIntro: "Everything you need to move from a first spark of inspiration to a name that feels truly right.", meanings: "Name Meanings", meaningsText: "Understand the feeling, history and story carried by every name.", urduMeanings: "Urdu Meanings", urduMeaningsText: "Explore names with clear, thoughtful Urdu meanings for easier discovery.", origins: "Origins & Cultures", originsText: "Discover where names come from and the traditions that shaped them.", religion: "Religion", religionText: "Find names connected to the faiths and traditions meaningful to you.", lucky: "Lucky Numbers", luckyText: "Browse an extra layer of character and symbolism behind each name.", rarePopular: "Rare & Popular Names", rarePopularText: "Compare timeless favorites with distinctive names waiting to be found.", purpose: "Our purpose", purposeTitle: "Helping you find a name that feels meaningful.", purposeText: "Choosing a name can be personal, joyful and sometimes overwhelming. Our goal is to make that journey easier by bringing useful context together in one calm, welcoming place, so every search can lead to a name with a story worth carrying forward.", begin: "Begin exploring" },
  notFound: { eyebrow: "A little detour", title: "Oops! This name seems to have wandered off.", description: "The page you’re looking for couldn’t be found. Let’s help you discover something beautiful instead.", explore: "Explore Names", home: "Go Home", keep: "Keep exploring", looking: "Looking for the perfect name?", suggestions: "Explore names by country, meaning, origin, or category.", discover: "Discover Names", quick: "Quick name links", girls: "Girls Names", boys: "Boys Names", unisex: "Unisex Names" },
  footer: { tagline: "Sweet, meaningful names from every corner of the world.", email: "Email address", join: "Join", joined: "You’re on the list", explore: "Explore", allNames: "All Names", girls: "Girls Names", boys: "Boys Names", unisex: "Unisex Names", guides: "Guides", meanings: "Name Meanings", origins: "Name Origins", lucky: "Lucky Numbers", islamic: "Islamic Names", finder: "Name Finder", countries: "Countries", info: "Info", about: "About Us", contact: "Contact", privacy: "Privacy Policy", terms: "Terms", disclaimer: "Disclaimer", backTop: "Back to top", newsletter: "Newsletter subscription" },
  common: { name: "Name", names: "Names", explore: "Explore", all: "All", loading: "Loading...", error: "Something went wrong. Please try again." },
  religion: { Islamic: "Islamic", Christian: "Christian", Jewish: "Jewish", Hindu: "Hindu", Sikh: "Sikh", Buddhist: "Buddhist", Other: "Other", None: "None" },
  popularity: { Rare: "Rare", Uncommon: "Uncommon", Popular: "Popular", "Very Popular": "Very Popular" },
} as const;

export default en;
