const es = {
 language:"Idioma",nav:{home:"Inicio",about:"Sobre nosotros",regions:"Regiones",categories:"Categorías",popular:"Nombres populares",search:"Buscar cualquier cosa...",menu:"Menú",main:"Navegación principal",clear:"Borrar búsqueda",searching:"Buscando...",noResults:"No hay resultados para «{query}»",type:{Name:"Nombre",Region:"Región",Category:"Categoría",Page:"Página"}},
 search:{placeholder:"Buscar nombre, significado, país u origen...",label:"Buscar nombres, significados, países u orígenes",button:"Buscar",notFound:"No se encontraron nombres",description:"No encontramos ese nombre. Prueba otra forma de escribirlo o explora la colección.",explore:"Explorar nombres",goHome:"Ir al inicio",start:"Empieza a escribir para buscar nombres.",tryCountry:"Prueba «France»",tryOrigin:"Prueba «Arabic»",tryCategory:"Prueba «Popular Names»"},
 home:{title:"Cada nombre guarda una historia.",description:"Explora miles de nombres por país, región, género, religión, origen y significado, y encuentra el que encaja contigo.",featured:"Nombres destacados",exploreRegion:"Explorar por región",discoverWorld:"Descubre nombres de todo el mundo",regionDescription:"Descubre nombres, significados y orígenes de distintos países y regiones.",meaningTitle:"Los nombres tienen significado antes de acompañar a alguien.",meaningDescription:"Empieza por una sensación, no por una escritura; explora nombres por su significado.",howTitle:"Tres caminos para encontrar un buen nombre.",searchHow:"Busca a tu manera",searchHowText:"Escribe un nombre, sonido, país o significado: la búsqueda entiende cada opción.",narrow:"Afina la búsqueda",narrowText:"Filtra por origen, religión, región o género.",save:"Guarda tus favoritos",saveText:"Crea una lista mientras exploras para no perder ningún nombre especial.",shortlist:"Guarda tus favoritos mientras exploras.",startSearch:"Empezar a buscar",trySearch:"Prueba {query}",exploreMore:"Explorar {region}",countriesCount:"{count} países",more:"+{count} más"},
 region:{europe:"Europa",middleEast:"Oriente Medio",southAsia:"Asia del Sur",eastAsia:"Asia Oriental",southeastAsia:"Sudeste Asiático",centralAsia:"Asia Central",africa:"África",northAmerica:"Norteamérica",latinAmerica:"Latinoamérica / Sudamérica",caribbean:"Caribe",oceania:"Oceanía / Australia",explore:"Explorar {region}",countries:"Países",regionLabel:"Región",names:"Nombres",chooseCountry:"Elige un país",selectCountry:"Elige un país para explorar sus nombres y tradiciones.",backHome:"Volver al inicio",exploreNames:"Explorar nombres"},
 country:{backTo:"Volver a {region}",hero:"Explora los nombres y las tradiciones de {country}.",namesFrom:"Nombres de {country}",discover:"Descubre nombres que cuentan historias.",description:"Explora los nombres, significados y orígenes de {country}.",search:"Buscar nombres de {country}...",filterGender:"Filtrar nombres por género",girls:"Niñas",boys:"Niños",both:"Unisex",religion:"Religión",origin:"Origen",popularity:"Popularidad",state:"Estado",city:"Ciudad",all:"Todos",nameCount:"{count} nombres",noNames:"No se encontraron nombres",noNamesHelp:"Prueba otra búsqueda o elige otra categoría.",moreNames:"Explora más nombres y tradiciones de {country}",traditionalBelief:"Creencia tradicional"},
 name:{back:"Volver a la búsqueda",discovery:"Descubre el nombre",genderName:"Nombre {gender} · {region}",meaning:"Significado",story:"Descubre la historia, el origen y el carácter de este nombre."},gender:{girl:"Niña",boy:"Niño",both:"Unisex",girlName:"Nombre femenino",boyName:"Nombre masculino",unisexName:"Nombre unisex"},
 detail:{country:"País",religion:"Religión",popularity:"Popularidad",luckyNumber:"Número de la suerte",meaning:"Significado",copy:"Copiar",copied:"Copiado ✓",share:"Compartir",linkCopied:"Enlace copiado",copyDetails:"Detalles del nombre copiados",shareDetails:"Detalles para compartir copiados",shareName:"Compartir {name}",copyName:"Copiar detalles de {name}"},
 about:{eyebrow:"Acerca de NameWorlds",title:"Cada nombre tiene una historia",intro:"NameWorlds te ayuda a descubrir nombres con significado, legado y personalidad. Explora nombres de todo el mundo, sus orígenes, significados en urdu, vínculos religiosos, números de la suerte e historias memorables.",explore:"Explorar nombres",starting:"Un buen punto de partida",offer:"Qué ofrecemos",offerIntro:"Todo lo que necesitas para pasar de una primera inspiración a un nombre que se sienta perfecto.",meanings:"Significados",meaningsText:"Comprende la emoción, la historia y el relato de cada nombre.",urduMeanings:"Significados en urdu",urduMeaningsText:"Explora nombres con significados en urdu claros y útiles.",origins:"Orígenes y culturas",originsText:"Descubre de dónde vienen los nombres y las tradiciones que los formaron.",religion:"Religión",religionText:"Encuentra nombres ligados a las creencias y tradiciones que valoras.",lucky:"Números de la suerte",luckyText:"Descubre otra dimensión simbólica y personal de cada nombre.",rarePopular:"Nombres raros y populares",rarePopularText:"Compara favoritos de siempre con nombres singulares por descubrir.",purpose:"Nuestro propósito",purposeTitle:"Ayudarte a encontrar un nombre con significado.",purposeText:"Elegir un nombre puede ser algo íntimo, alegre y a veces abrumador. Queremos facilitar el camino reuniendo contexto útil en un espacio tranquilo y acogedor, para que cada búsqueda pueda llevarte a una historia que merezca perdurar.",begin:"Empezar a explorar"},
 notFound:{eyebrow:"Un pequeño desvío",title:"¡Vaya! Parece que este nombre se ha perdido.",description:"No encontramos la página que buscas. Descubramos algo bonito en su lugar.",explore:"Explorar nombres",home:"Ir al inicio",keep:"Seguir explorando",looking:"¿Buscas el nombre perfecto?",suggestions:"Explora nombres por país, significado, origen o categoría.",discover:"Descubrir nombres",quick:"Enlaces rápidos de nombres",girls:"Nombres de niña",boys:"Nombres de niño",unisex:"Nombres unisex"},
 footer:{tagline:"Nombres dulces y significativos de todos los rincones del mundo.",email:"Correo electrónico",join:"Unirme",joined:"Ya estás en la lista",explore:"Explorar",allNames:"Todos los nombres",girls:"Nombres de niña",boys:"Nombres de niño",unisex:"Nombres unisex",guides:"Guías",meanings:"Significados",origins:"Orígenes",lucky:"Números de la suerte",islamic:"Nombres islámicos",finder:"Buscador de nombres",countries:"Países",info:"Información",about:"Sobre nosotros",contact:"Contacto",privacy:"Privacidad",terms:"Condiciones",disclaimer:"Aviso legal",backTop:"Volver arriba",newsletter:"Suscripción al boletín"},common:{name:"Nombre",names:"Nombres",explore:"Explorar",all:"Todos",loading:"Cargando...",error:"Algo salió mal. Inténtalo de nuevo."},religion:{Islamic:"Islámica",Christian:"Cristiana",Jewish:"Judía",Hindu:"Hindú",Sikh:"Sij",Buddhist:"Budista",Other:"Otra",None:"Ninguna"},popularity:{Rare:"Raro",Uncommon:"Poco común",Popular:"Popular","Very Popular":"Muy popular"}
} as const;
export default es;
