const hi = {
 language:"भाषा",nav:{home:"मुखपृष्ठ",about:"हमारे बारे में",regions:"क्षेत्र",categories:"श्रेणियाँ",popular:"लोकप्रिय नाम",search:"कुछ भी खोजें...",menu:"मेनू",main:"मुख्य नेविगेशन",clear:"खोज मिटाएँ",searching:"खोज जारी है...",noResults:"“{query}” के लिए कोई परिणाम नहीं मिला",type:{Name:"नाम",Region:"क्षेत्र",Category:"श्रेणी",Page:"पृष्ठ"}},
 search:{placeholder:"नाम, अर्थ, देश या उत्पत्ति खोजें...",label:"नाम, अर्थ, देश या उत्पत्ति खोजें",button:"खोजें",notFound:"कोई नाम नहीं मिला",description:"यह नाम नहीं मिला। वर्तनी बदलकर देखें या पूरी सूची देखें।",explore:"नाम खोजें",goHome:"मुखपृष्ठ पर जाएँ",start:"नाम खोजने के लिए लिखना शुरू करें।",tryCountry:"“France” आज़माएँ",tryOrigin:"“Arabic” आज़माएँ",tryCategory:"“Popular Names” आज़माएँ"},
 home:{title:"हर नाम अपने साथ एक कहानी लाता है।",description:"देश, क्षेत्र, लिंग, धर्म, उत्पत्ति और अर्थ के अनुसार हज़ारों नाम खोजें और अपने लिए सही नाम पाएँ।",featured:"चुनिंदा नाम",exploreRegion:"क्षेत्र के अनुसार खोजें",discoverWorld:"दुनिया भर के नाम जानें",regionDescription:"अलग-अलग देशों और क्षेत्रों के सुंदर नाम, अर्थ और उत्पत्ति खोजें।",meaningTitle:"नाम किसी व्यक्ति की पहचान बनने से पहले ही अर्थ रखते हैं।",meaningDescription:"वर्तनी के बजाय भावना से शुरुआत करें और अर्थ के अनुसार नाम देखें।",howTitle:"खोज के तीन रास्ते, एक अच्छा नाम।",searchHow:"अपने तरीके से खोजें",searchHowText:"नाम, ध्वनि, देश या अर्थ लिखें; खोज इन सभी को समझती है।",narrow:"विकल्प सीमित करें",narrowText:"उत्पत्ति, धर्म, क्षेत्र या लिंग के अनुसार छाँटें।",save:"पसंदीदा नाम सहेजें",saveText:"खोजते समय अपनी पसंद की सूची बनाएँ ताकि कोई अच्छा नाम छूट न जाए।",shortlist:"खोजते समय पसंदीदा नाम सहेजें।",startSearch:"खोज शुरू करें",trySearch:"{query} आज़माएँ",exploreMore:"{region} देखें",countriesCount:"{count} देश",more:"और {count}"},
 region:{europe:"यूरोप",middleEast:"मध्य पूर्व",southAsia:"दक्षिण एशिया",eastAsia:"पूर्वी एशिया",southeastAsia:"दक्षिण-पूर्व एशिया",centralAsia:"मध्य एशिया",africa:"अफ़्रीका",northAmerica:"उत्तरी अमेरिका",latinAmerica:"लैटिन अमेरिका / दक्षिण अमेरिका",caribbean:"कैरेबियन",oceania:"ओशिनिया / ऑस्ट्रेलिया",explore:"{region} देखें",countries:"देश",regionLabel:"क्षेत्र",names:"नाम",chooseCountry:"देश चुनें",selectCountry:"नाम और नामकरण परंपराएँ देखने के लिए देश चुनें।",backHome:"मुखपृष्ठ पर लौटें",exploreNames:"नाम देखें"},
 country:{backTo:"{region} पर लौटें",hero:"{country} के नाम और नामकरण परंपराएँ देखें।",namesFrom:"{country} के नाम",discover:"कहानी कहने वाले नाम खोजें।",description:"{country} के सुंदर नाम, उनके अर्थ और उत्पत्ति देखें।",search:"{country} में नाम खोजें...",filterGender:"लिंग के अनुसार नाम छाँटें",girls:"लड़कियाँ",boys:"लड़के",both:"उभयलिंगी",religion:"धर्म",origin:"उत्पत्ति",popularity:"लोकप्रियता",state:"राज्य",city:"शहर",all:"सभी",nameCount:"{count} नाम",noNames:"कोई नाम नहीं मिला",noNamesHelp:"दूसरी खोज करें या अलग श्रेणी चुनें।",moreNames:"{country} के और नाम व परंपराएँ देखें",traditionalBelief:"पारंपरिक मान्यता"},
 name:{back:"खोज पर लौटें",discovery:"नाम की जानकारी",genderName:"{gender} नाम · {region}",meaning:"अर्थ",story:"इस सुंदर नाम की कहानी, उत्पत्ति और विशेषताएँ जानें।"},gender:{girl:"लड़की",boy:"लड़का",both:"उभयलिंगी",girlName:"लड़की का नाम",boyName:"लड़के का नाम",unisexName:"उभयलिंगी नाम"},
 detail:{country:"देश",religion:"धर्म",popularity:"लोकप्रियता",luckyNumber:"शुभ अंक",meaning:"अर्थ",copy:"कॉपी करें",copied:"कॉपी हुआ ✓",share:"साझा करें",linkCopied:"लिंक कॉपी हुआ",copyDetails:"नाम की जानकारी कॉपी हुई",shareDetails:"साझा करने की जानकारी कॉपी हुई",shareName:"{name} साझा करें",copyName:"{name} की जानकारी कॉपी करें"},
 about:{eyebrow:"NameWorlds के बारे में",title:"हर नाम की एक कहानी है",intro:"NameWorlds आपको अर्थ, विरासत और विशेषताओं वाले नाम खोजने में मदद करता है। दुनिया भर के नाम, उनकी उत्पत्ति, उर्दू अर्थ, धार्मिक संबंध, शुभ अंक और यादगार कहानियाँ जानें।",explore:"नाम देखें",starting:"एक सार्थक शुरुआत",offer:"हम क्या देते हैं",offerIntro:"पहली प्रेरणा से लेकर सही लगने वाले नाम तक पहुँचने के लिए सब कुछ।",meanings:"नामों के अर्थ",meaningsText:"हर नाम की भावना, इतिहास और कहानी समझें।",urduMeanings:"उर्दू अर्थ",urduMeaningsText:"आसान खोज के लिए स्पष्ट उर्दू अर्थों वाले नाम देखें।",origins:"उत्पत्ति और संस्कृतियाँ",originsText:"जानें कि नाम कहाँ से आए और किन परंपराओं ने उन्हें आकार दिया।",religion:"धर्म",religionText:"अपने लिए महत्वपूर्ण आस्थाओं और परंपराओं से जुड़े नाम खोजें।",lucky:"शुभ अंक",luckyText:"हर नाम के प्रतीक और व्यक्तित्व का एक और पहलू देखें।",rarePopular:"दुर्लभ और लोकप्रिय नाम",rarePopularText:"सदा पसंद किए जाने वाले और अनोखे नामों की तुलना करें।",purpose:"हमारा उद्देश्य",purposeTitle:"आपको अर्थपूर्ण नाम खोजने में मदद करना।",purposeText:"नाम चुनना निजी, आनंददायक और कभी-कभी कठिन हो सकता है। हम उपयोगी जानकारी को एक शांत, स्वागतपूर्ण जगह पर लाकर यह सफ़र आसान बनाते हैं, ताकि हर खोज ऐसी कहानी तक पहुँचा सके जिसे आगे बढ़ाया जाए।",begin:"खोज शुरू करें"},
 notFound:{eyebrow:"एक छोटा मोड़",title:"अरे! लगता है यह नाम कहीं खो गया।",description:"आपका पृष्ठ नहीं मिला। आइए इसके बजाय कुछ सुंदर खोजें।",explore:"नाम देखें",home:"मुखपृष्ठ",keep:"खोज जारी रखें",looking:"क्या आप सही नाम खोज रहे हैं?",suggestions:"देश, अर्थ, उत्पत्ति या श्रेणी के अनुसार नाम देखें।",discover:"नाम खोजें",quick:"नामों के त्वरित लिंक",girls:"लड़कियों के नाम",boys:"लड़कों के नाम",unisex:"उभयलिंगी नाम"},
 footer:{tagline:"दुनिया के हर कोने से सुंदर और अर्थपूर्ण नाम।",email:"ईमेल पता",join:"जुड़ें",joined:"आप सूची में शामिल हैं",explore:"खोजें",allNames:"सभी नाम",girls:"लड़कियों के नाम",boys:"लड़कों के नाम",unisex:"उभयलिंगी नाम",guides:"मार्गदर्शिकाएँ",meanings:"नामों के अर्थ",origins:"नामों की उत्पत्ति",lucky:"शुभ अंक",islamic:"इस्लामी नाम",finder:"नाम खोजक",countries:"देश",info:"जानकारी",about:"हमारे बारे में",contact:"संपर्क",privacy:"गोपनीयता नीति",terms:"नियम",disclaimer:"अस्वीकरण",backTop:"ऊपर जाएँ",newsletter:"समाचार-पत्र सदस्यता"},common:{name:"नाम",names:"नाम",explore:"खोजें",all:"सभी",loading:"लोड हो रहा है...",error:"कुछ गड़बड़ हुई। कृपया फिर कोशिश करें।"},religion:{Islamic:"इस्लामी",Christian:"ईसाई",Jewish:"यहूदी",Hindu:"हिंदू",Sikh:"सिख",Buddhist:"बौद्ध",Other:"अन्य",None:"कोई नहीं"},popularity:{Rare:"दुर्लभ",Uncommon:"कम प्रचलित",Popular:"लोकप्रिय","Very Popular":"बहुत लोकप्रिय"}
} as const;
export default hi;
