const tr = {
 language:"Dil",nav:{home:"Ana Sayfa",about:"Hakkımızda",regions:"Bölgeler",categories:"Kategoriler",popular:"Popüler İsimler",search:"Her şeyi ara...",menu:"Menü",main:"Ana gezinme",clear:"Aramayı temizle",searching:"Aranıyor...",noResults:"“{query}” için sonuç bulunamadı",type:{Name:"İsim",Region:"Bölge",Category:"Kategori",Page:"Sayfa"}},
 search:{placeholder:"İsim, anlam, ülke veya köken ara...",label:"İsimleri, anlamları, ülkeleri ve kökenleri ara",button:"Ara",notFound:"İsim bulunamadı",description:"Bu ismi bulamadık. Farklı yazmayı deneyin veya tüm koleksiyona göz atın.",explore:"İsimleri keşfet",goHome:"Ana sayfa",start:"İsimleri aramak için yazmaya başlayın.",tryCountry:"“France” deneyin",tryOrigin:"“Arabic” deneyin",tryCategory:"“Popular Names” deneyin"},
 home:{title:"Her isim bir hikâye taşır.",description:"Ülke, bölge, cinsiyet, din, köken ve anlama göre binlerce ismi keşfedin; size uygun olanı bulun.",featured:"Öne çıkan isimler",exploreRegion:"Bölgeye göre keşfet",discoverWorld:"Dünyanın dört yanından isimleri keşfedin",regionDescription:"Farklı ülke ve bölgelerden güzel isimleri, anlamlarını ve kökenlerini keşfedin.",meaningTitle:"İsimler, bir kişiye eşlik etmeden önce anlam taşır.",meaningDescription:"Yazılıştan değil duygudan başlayın; isimleri anlamlarına göre keşfedin.",howTitle:"İyi bir isme ulaşmanın üç yolu.",searchHow:"Aklınızdaki gibi arayın",searchHowText:"Bir isim, ses, ülke ya da anlam yazın; arama hepsini anlar.",narrow:"Seçenekleri daraltın",narrowText:"Köken, din, bölge veya cinsiyete göre filtreleyin.",save:"Beğendiklerinizi kaydedin",saveText:"Ararken kısa bir liste oluşturun, güzel isimleri gözden kaçırmayın.",shortlist:"Gezerken beğendiğiniz isimleri kaydedin.",startSearch:"Aramaya başla",trySearch:"{query} deneyin",exploreMore:"{region} bölgesini keşfet",countriesCount:"{count} ülke",more:"+{count} ülke daha"},
 region:{europe:"Avrupa",middleEast:"Orta Doğu",southAsia:"Güney Asya",eastAsia:"Doğu Asya",southeastAsia:"Güneydoğu Asya",centralAsia:"Orta Asya",africa:"Afrika",northAmerica:"Kuzey Amerika",latinAmerica:"Latin Amerika / Güney Amerika",caribbean:"Karayipler",oceania:"Okyanusya / Avustralya",explore:"{region} bölgesini keşfet",countries:"Ülkeler",regionLabel:"Bölge",names:"İsimler",chooseCountry:"Bir ülke seçin",selectCountry:"İsimlerini ve adlandırma geleneklerini keşfetmek için bir ülke seçin.",backHome:"Ana sayfaya dön",exploreNames:"İsimleri keşfet"},
 country:{backTo:"{region} bölgesine dön",hero:"{country} isimlerini ve adlandırma geleneklerini keşfedin.",namesFrom:"{country} isimleri",discover:"Hikâyesi olan isimleri keşfedin.",description:"{country} isimlerini, anlamlarını ve kökenlerini keşfedin.",search:"{country} isimlerinde ara...",filterGender:"Cinsiyete göre filtrele",girls:"Kız",boys:"Erkek",both:"Unisex",religion:"Din",origin:"Köken",popularity:"Popülerlik",state:"Eyalet",city:"Şehir",all:"Tümü",nameCount:"{count} isim",noNames:"İsim bulunamadı",noNamesHelp:"Başka bir arama deneyin veya farklı bir kategori seçin.",moreNames:"{country} isimlerini ve geleneklerini keşfetmeye devam edin",traditionalBelief:"Geleneksel inanış"},
 name:{back:"Aramaya dön",discovery:"İsim keşfi",genderName:"{gender} ismi · {region}",meaning:"Anlam",story:"Bu güzel ismin hikâyesini, kökenini ve karakterini keşfedin."},gender:{girl:"Kız",boy:"Erkek",both:"Unisex",girlName:"Kız ismi",boyName:"Erkek ismi",unisexName:"Unisex isim"},
 detail:{country:"Ülke",religion:"Din",popularity:"Popülerlik",luckyNumber:"Şanslı sayı",meaning:"Anlam",copy:"Kopyala",copied:"Kopyalandı ✓",share:"Paylaş",linkCopied:"Bağlantı kopyalandı",copyDetails:"İsim bilgileri kopyalandı",shareDetails:"Paylaşım bilgileri kopyalandı",shareName:"{name} ismini paylaş",copyName:"{name} bilgilerini kopyala"},
 about:{eyebrow:"NameWorlds Hakkında",title:"Her İsmin Bir Hikâyesi Var",intro:"NameWorlds anlamı, mirası ve karakteri olan isimleri keşfetmenize yardımcı olur. Dünyanın dört yanından isimleri, kökenlerini, Urduca anlamlarını, dinî bağlantılarını, şanslı sayılarını ve hikâyelerini keşfedin.",explore:"İsimleri keşfet",starting:"Düşünceli bir başlangıç",offer:"Neler Sunuyoruz",offerIntro:"İlk ilhamdan size gerçekten doğru gelen bir isme ulaşmak için ihtiyacınız olan her şey.",meanings:"İsim Anlamları",meaningsText:"Her ismin taşıdığı duyguyu, tarihi ve hikâyeyi anlayın.",urduMeanings:"Urduca Anlamlar",urduMeaningsText:"Kolay keşif için açık Urduca anlamlara sahip isimleri inceleyin.",origins:"Kökenler ve Kültürler",originsText:"İsimlerin nereden geldiğini ve onları şekillendiren gelenekleri öğrenin.",religion:"Din",religionText:"Sizin için önemli inanç ve geleneklerle bağlantılı isimleri bulun.",lucky:"Şanslı Sayılar",luckyText:"Her ismin sembolik ve kişisel yönünü keşfedin.",rarePopular:"Nadir ve Popüler İsimler",rarePopularText:"Zamansız favorileri keşfedilmeyi bekleyen özgün isimlerle karşılaştırın.",purpose:"Amacımız",purposeTitle:"Anlamlı hissettiren bir isim bulmanıza yardımcı olmak.",purposeText:"İsim seçmek kişisel, neşeli ve bazen zorlayıcı olabilir. Yararlı bilgileri sakin ve sıcak bir yerde bir araya getirerek bu yolculuğu kolaylaştırmak, her aramanın aktarılmaya değer bir hikâyeye ulaşmasını sağlamak istiyoruz.",begin:"Keşfetmeye başla"},
 notFound:{eyebrow:"Küçük bir sapma",title:"Eyvah! Bu isim kaybolmuş gibi görünüyor.",description:"Aradığınız sayfa bulunamadı. Bunun yerine güzel bir şey keşfedelim.",explore:"İsimleri keşfet",home:"Ana sayfa",keep:"Keşfetmeye devam et",looking:"Mükemmel ismi mi arıyorsunuz?",suggestions:"İsimleri ülke, anlam, köken veya kategoriye göre keşfedin.",discover:"İsimleri keşfet",quick:"İsimlere hızlı bağlantılar",girls:"Kız isimleri",boys:"Erkek isimleri",unisex:"Unisex isimler"},
 footer:{tagline:"Dünyanın her köşesinden güzel ve anlamlı isimler.",email:"E-posta adresi",join:"Katıl",joined:"Listeye eklendiniz",explore:"Keşfet",allNames:"Tüm İsimler",girls:"Kız isimleri",boys:"Erkek isimleri",unisex:"Unisex isimler",guides:"Rehberler",meanings:"İsim Anlamları",origins:"İsim Kökenleri",lucky:"Şanslı Sayılar",islamic:"İslami İsimler",finder:"İsim Bulucu",countries:"Ülkeler",info:"Bilgi",about:"Hakkımızda",contact:"İletişim",privacy:"Gizlilik Politikası",terms:"Koşullar",disclaimer:"Yasal Uyarı",backTop:"Başa dön",newsletter:"Bülten aboneliği"},common:{name:"İsim",names:"İsimler",explore:"Keşfet",all:"Tümü",loading:"Yükleniyor...",error:"Bir sorun oluştu. Lütfen tekrar deneyin."},religion:{Islamic:"İslami",Christian:"Hristiyan",Jewish:"Yahudi",Hindu:"Hindu",Sikh:"Sih",Buddhist:"Budist",Other:"Diğer",None:"Yok"},popularity:{Rare:"Nadir",Uncommon:"Az bilinen",Popular:"Popüler","Very Popular":"Çok popüler"}
} as const;
export default tr;
