const ur = {
  language: "زبان", nav: { home: "صفحۂ اول", about: "ہمارے بارے میں", regions: "علاقے", categories: "اقسام", popular: "مقبول نام", search: "کچھ بھی تلاش کریں...", menu: "مینو", main: "مرکزی نیویگیشن", clear: "تلاش صاف کریں", searching: "تلاش جاری ہے...", noResults: "“{query}” کے لیے کوئی نتیجہ نہیں ملا", type: { Name: "نام", Region: "علاقہ", Category: "قسم", Page: "صفحہ" } },
  search: { placeholder: "نام، معنی، ملک یا ماخذ تلاش کریں...", label: "نام، معنی، ملک یا ماخذ تلاش کریں", button: "تلاش", notFound: "کوئی نام نہیں ملا", description: "یہ نام نہیں ملا۔ ہجے بدل کر دیکھیں یا پوری فہرست دیکھیں۔", explore: "نام دیکھیں", goHome: "صفحۂ اول", start: "نام تلاش کرنے کے لیے لکھنا شروع کریں۔", tryCountry: "“France” آزمائیں", tryOrigin: "“Arabic” آزمائیں", tryCategory: "“Popular Names” آزمائیں" },
  home: { title: "ہر نام اپنے ساتھ ایک کہانی رکھتا ہے۔", description: "ملک، خطے، جنس، مذہب، ماخذ اور معنی کے لحاظ سے ہزاروں نام تلاش کریں اور اپنے لیے موزوں نام ڈھونڈیں۔", featured: "منتخب نام", exploreRegion: "علاقے کے لحاظ سے دیکھیں", discoverWorld: "دنیا بھر کے نام دریافت کریں", regionDescription: "مختلف ممالک اور علاقوں کے خوبصورت نام، معنی اور ماخذ دریافت کریں۔", meaningTitle: "نام کسی شخصیت سے جڑنے سے پہلے ہی معنی رکھتے ہیں۔", meaningDescription: "ہجے کے بجائے احساس سے آغاز کریں اور معنی کے مطابق نام دیکھیں۔", howTitle: "تلاش کے تین راستے، ایک اچھا نام۔", searchHow: "اپنے انداز سے تلاش کریں", searchHowText: "نام، آواز، ملک یا معنی لکھیں؛ تلاش ان سب کو سمجھتی ہے۔", narrow: "انتخاب محدود کریں", narrowText: "ماخذ، مذہب، علاقے یا جنس کے لحاظ سے فہرست چھانٹیں۔", save: "پسندیدہ نام محفوظ رکھیں", saveText: "تلاش کے دوران اپنی پسند کی فہرست بنائیں تاکہ کوئی اچھا نام رہ نہ جائے۔", shortlist: "تلاش کے دوران اپنی پسند محفوظ رکھیں۔", startSearch: "تلاش شروع کریں", trySearch: "{query} آزمائیں", exploreMore: "{region} دیکھیں", countriesCount: "{count} ممالک", more: "+{count} مزید" },
  region: { europe: "یورپ", middleEast: "مشرقِ وسطیٰ", southAsia: "جنوبی ایشیا", eastAsia: "مشرقی ایشیا", southeastAsia: "جنوب مشرقی ایشیا", centralAsia: "وسطی ایشیا", africa: "افریقہ", northAmerica: "شمالی امریکا", latinAmerica: "لاطینی امریکا / جنوبی امریکا", caribbean: "کیریبین", oceania: "اوشیانا / آسٹریلیا", explore: "{region} دیکھیں", countries: "ممالک", regionLabel: "علاقہ", names: "نام", chooseCountry: "ایک ملک منتخب کریں", selectCountry: "نام اور نام رکھنے کی روایات دیکھنے کے لیے ملک منتخب کریں۔", backHome: "صفحۂ اول پر واپس", exploreNames: "نام دیکھیں" },
  country: { backTo: "{region} پر واپس", hero: "{country} کے نام اور نام رکھنے کی روایات دیکھیں۔", namesFrom: "{country} کے نام", discover: "کہانی سنانے والے نام دریافت کریں۔", description: "{country} کے خوبصورت نام، معنی اور ماخذ دیکھیں۔", search: "{country} میں نام تلاش کریں...", filterGender: "جنس کے لحاظ سے نام چھانٹیں", girls: "لڑکیاں", boys: "لڑکے", both: "دونوں", religion: "مذہب", origin: "ماخذ", popularity: "مقبولیت", state: "ریاست", city: "شہر", all: "سب", nameCount: "{count} نام", noNames: "کوئی نام نہیں ملا", noNamesHelp: "دوسری تلاش کریں یا کوئی اور قسم منتخب کریں۔", moreNames: "{country} کے مزید نام اور روایات دیکھیں", traditionalBelief: "روایتی عقیدہ" },
  name: { back: "تلاش پر واپس", discovery: "نام کی دریافت", genderName: "{gender} نام · {region}", meaning: "معنی", story: "اس خوبصورت نام کی کہانی، ماخذ اور خصوصیات جانیں۔" }, gender: { girl: "لڑکی", boy: "لڑکا", both: "مشترک", girlName: "لڑکی کا نام", boyName: "لڑکے کا نام", unisexName: "مشترک نام" },
  detail: { country: "ملک", religion: "مذہب", popularity: "مقبولیت", luckyNumber: "خوش قسمت عدد", meaning: "معنی", copy: "کاپی", copied: "کاپی ہوگیا ✓", share: "شیئر", linkCopied: "لنک کاپی ہوگیا", copyDetails: "نام کی تفصیل کاپی ہوگئی", shareDetails: "شیئر کی تفصیل کاپی ہوگئی", shareName: "{name} شیئر کریں", copyName: "{name} کی تفصیل کاپی کریں" },
  about: { eyebrow: "NameWorlds کے بارے میں", title: "ہر نام کی ایک کہانی ہے", intro: "NameWorlds آپ کو معنی، ورثے اور خصوصیات والے نام دریافت کرنے میں مدد دیتا ہے۔ دنیا بھر کے نام، ان کے ماخذ، اردو معنی، مذہبی تعلقات اور خوش قسمت اعداد دیکھیں۔", explore: "نام دیکھیں", starting: "ایک بامعنی آغاز", offer: "ہم کیا پیش کرتے ہیں", offerIntro: "ابتدائی خیال سے ایسے نام تک پہنچنے کے لیے سب کچھ جو آپ کو درست محسوس ہو۔", meanings: "ناموں کے معنی", meaningsText: "ہر نام میں موجود احساس، تاریخ اور کہانی سمجھیں۔", urduMeanings: "اردو معنی", urduMeaningsText: "آسان تلاش کے لیے واضح اردو معنی والے نام دیکھیں۔", origins: "ماخذ اور ثقافتیں", originsText: "ناموں کے ماخذ اور انہیں تشکیل دینے والی روایات جانیں۔", religion: "مذہب", religionText: "اپنے لیے اہم عقائد اور روایات سے جڑے نام تلاش کریں۔", lucky: "خوش قسمت اعداد", luckyText: "ہر نام کی علامت اور شخصیت کا ایک اور پہلو دیکھیں۔", rarePopular: "نایاب اور مقبول نام", rarePopularText: "ہمیشہ پسند کیے جانے والے اور منفرد ناموں کا موازنہ کریں۔", purpose: "ہمارا مقصد", purposeTitle: "ایسا نام ڈھونڈنے میں مدد جو معنی خیز ہو۔", purposeText: "نام چننا ذاتی، خوشگوار اور کبھی مشکل ہوسکتا ہے۔ ہمارا مقصد مفید معلومات ایک پُرسکون جگہ پر جمع کرکے اس سفر کو آسان بنانا ہے۔", begin: "دریافت شروع کریں" },
  notFound: { eyebrow: "ایک چھوٹا سا موڑ", title: "اوہ! لگتا ہے یہ نام کہیں کھو گیا ہے۔", description: "مطلوبہ صفحہ نہیں ملا۔ آئیے اس کے بجائے کچھ خوبصورت دریافت کریں۔", explore: "نام دیکھیں", home: "صفحۂ اول", keep: "دیکھتے رہیں", looking: "کیا آپ بہترین نام تلاش کر رہے ہیں؟", suggestions: "ملک، معنی، ماخذ یا قسم کے لحاظ سے نام دیکھیں۔", discover: "نام دریافت کریں", quick: "ناموں کے فوری روابط", girls: "لڑکیوں کے نام", boys: "لڑکوں کے نام", unisex: "مشترک نام" },
  footer: { tagline: "دنیا کے ہر کونے سے پیارے اور بامعنی نام۔", email: "ای میل پتہ", join: "شامل ہوں", joined: "آپ فہرست میں شامل ہیں", explore: "دریافت کریں", allNames: "تمام نام", girls: "لڑکیوں کے نام", boys: "لڑکوں کے نام", unisex: "مشترک نام", guides: "رہنما", meanings: "ناموں کے معنی", origins: "ناموں کے ماخذ", lucky: "خوش قسمت اعداد", islamic: "اسلامی نام", finder: "نام تلاش کریں", countries: "ممالک", info: "معلومات", about: "ہمارے بارے میں", contact: "رابطہ", privacy: "رازداری کی پالیسی", terms: "شرائط", disclaimer: "دستبرداری", backTop: "اوپر جائیں", newsletter: "خبرنامے کی رکنیت" },
  common: { name: "نام", names: "نام", explore: "دریافت کریں", all: "سب", loading: "لوڈ ہو رہا ہے...", error: "کچھ غلط ہوگیا۔ دوبارہ کوشش کریں۔" }, religion: { Islamic: "اسلامی", Christian: "عیسائی", Jewish: "یہودی", Hindu: "ہندو", Sikh: "سکھ", Buddhist: "بدھ", Other: "دیگر", None: "کوئی نہیں" }, popularity: { Rare: "نایاب", Uncommon: "کم عام", Popular: "مقبول", "Very Popular": "بہت مقبول" }
} as const;
export default ur;
