const zh = {
 language:"语言", nav:{home:"首页",about:"关于我们",regions:"地区",categories:"类别",popular:"热门名字",search:"搜索任何内容...",menu:"菜单",main:"主导航",clear:"清除搜索",searching:"正在搜索...",noResults:"没有找到“{query}”的结果",type:{Name:"名字",Region:"地区",Category:"类别",Page:"页面"}},
 search:{placeholder:"搜索名字、含义、国家或来源...",label:"搜索名字、含义、国家或来源",button:"搜索",notFound:"未找到名字",description:"没有找到这个名字。请尝试其他拼写，或浏览全部内容。",explore:"探索名字",goHome:"返回首页",start:"开始输入以搜索名字。",tryCountry:"试试“France”",tryOrigin:"试试“Arabic”",tryCategory:"试试“Popular Names”"},
 home:{title:"每个名字都有自己的故事。",description:"按国家、地区、性别、宗教、来源和含义探索数千个名字，找到适合你的名字。",featured:"精选名字",exploreRegion:"按地区探索",discoverWorld:"探索世界各地的名字",regionDescription:"探索不同国家和地区的优美名字、含义与来源。",meaningTitle:"名字先有含义，而后伴随一生。",meaningDescription:"从感受而非拼写开始，按含义浏览名字。",howTitle:"三种探索方式，一个好名字。",searchHow:"按你的想法搜索",searchHowText:"输入名字、读音、国家或含义，搜索都能识别。",narrow:"缩小范围",narrowText:"按来源、宗教、地区或性别筛选。",save:"收藏喜欢的名字",saveText:"浏览时保存心仪名字，不错过任何好选择。",shortlist:"浏览时保存你的心仪名单。",startSearch:"开始搜索",trySearch:"试试{query}",exploreMore:"探索{region}",countriesCount:"{count}个国家",more:"另有{count}个"},
 region:{europe:"欧洲",middleEast:"中东",southAsia:"南亚",eastAsia:"东亚",southeastAsia:"东南亚",centralAsia:"中亚",africa:"非洲",northAmerica:"北美洲",latinAmerica:"拉丁美洲 / 南美洲",caribbean:"加勒比地区",oceania:"大洋洲 / 澳大利亚",explore:"探索{region}",countries:"国家",regionLabel:"地区",names:"名字",chooseCountry:"选择国家",selectCountry:"选择一个国家，探索当地名字和命名传统。",backHome:"返回首页",exploreNames:"探索名字"},
 country:{backTo:"返回{region}",hero:"探索{country}的名字与命名传统。",namesFrom:"来自{country}的名字",discover:"发现讲述故事的名字。",description:"探索{country}优美的名字、含义与来源。",search:"搜索{country}的名字...",filterGender:"按性别筛选名字",girls:"女孩",boys:"男孩",both:"中性",religion:"宗教",origin:"来源",popularity:"流行度",state:"州/省",city:"城市",all:"全部",nameCount:"{count}个名字",noNames:"未找到名字",noNamesHelp:"请尝试其他搜索，或选择其他类别。",moreNames:"探索更多{country}名字与命名传统",traditionalBelief:"传统信念"},
 name:{back:"返回搜索",discovery:"名字探索",genderName:"{gender}名字 · {region}",meaning:"含义",story:"了解这个名字的故事、来源与特点。"},gender:{girl:"女孩",boy:"男孩",both:"中性",girlName:"女孩名字",boyName:"男孩名字",unisexName:"中性名字"},
 detail:{country:"国家",religion:"宗教",popularity:"流行度",luckyNumber:"幸运数字",meaning:"含义",copy:"复制",copied:"已复制 ✓",share:"分享",linkCopied:"链接已复制",copyDetails:"名字详情已复制",shareDetails:"分享内容已复制",shareName:"分享{name}",copyName:"复制{name}的详情"},
 about:{eyebrow:"关于NameWorlds",title:"每个名字都有故事",intro:"NameWorlds帮助你发现有含义、有传承、有个性的名字。探索世界各地名字的来源、乌尔都语含义、宗教关联、幸运数字与动人故事。",explore:"探索名字",starting:"用心开启探索",offer:"我们提供什么",offerIntro:"从灵感闪现到找到真正合适的名字，你需要的内容都在这里。",meanings:"名字含义",meaningsText:"了解每个名字承载的情感、历史与故事。",urduMeanings:"乌尔都语含义",urduMeaningsText:"通过清晰的乌尔都语释义轻松探索名字。",origins:"来源与文化",originsText:"了解名字的起源及塑造它们的传统。",religion:"宗教",religionText:"寻找与你珍视的信仰和传统相关的名字。",lucky:"幸运数字",luckyText:"探索名字个性与象征意义的另一面。",rarePopular:"罕见与热门名字",rarePopularText:"比较经典常见的名字与独特新颖的选择。",purpose:"我们的目标",purposeTitle:"帮你找到真正有意义的名字。",purposeText:"选择名字既私密又令人欣喜，有时也会让人不知所措。我们将实用信息汇集在宁静友好的空间，让每次搜索都可能发现值得传承的故事。",begin:"开始探索"},
 notFound:{eyebrow:"小小的岔路",title:"哎呀！这个名字似乎走丢了。",description:"找不到你访问的页面。让我们一起发现其他美好的内容。",explore:"探索名字",home:"返回首页",keep:"继续探索",looking:"正在寻找理想的名字吗？",suggestions:"按国家、含义、来源或类别探索名字。",discover:"发现名字",quick:"名字快捷链接",girls:"女孩名字",boys:"男孩名字",unisex:"中性名字"},
 footer:{tagline:"来自世界各地，甜美而有意义的名字。",email:"电子邮箱",join:"订阅",joined:"已加入订阅名单",explore:"探索",allNames:"所有名字",girls:"女孩名字",boys:"男孩名字",unisex:"中性名字",guides:"指南",meanings:"名字含义",origins:"名字来源",lucky:"幸运数字",islamic:"伊斯兰名字",finder:"名字查找",countries:"国家",info:"信息",about:"关于我们",contact:"联系我们",privacy:"隐私政策",terms:"条款",disclaimer:"免责声明",backTop:"返回顶部",newsletter:"订阅邮件"},common:{name:"名字",names:"名字",explore:"探索",all:"全部",loading:"正在加载...",error:"出错了，请重试。"},religion:{Islamic:"伊斯兰",Christian:"基督教",Jewish:"犹太教",Hindu:"印度教",Sikh:"锡克教",Buddhist:"佛教",Other:"其他",None:"无"},popularity:{Rare:"罕见",Uncommon:"较少见",Popular:"流行","Very Popular":"非常流行"}
} as const;
export default zh;
